### ISSUE TITLE
Spacemesh's rand is not concurrent safe

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1612]
Calling to spacemesh's rand concurrently is not safe. May result in a panic of "index out of range".

**Comment by gavraz** [comment]
We call to rand.Seed in ntpTimeDrift during runtime.
We got the following panic because of it:
ERROR
       	t  M	harness: the err is: panic: runtime error: index out of range
goroutine 28814 [running]:
math/rand.(*rngSource).Uint64(...)
	/usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc00015ca00, 0x1f74caedae4)
	/usr/local/go/src/math/rand/rng.go:234 +0x89
math/rand.(*Rand).Int63(0xc000162cf0, 0xc005ed56a0)
	/usr/local/go/src/math/rand/rand.go:85 +0x33
math/rand.(*Rand).Int(0xc000162cf0, 0x1ec9c1e7e40)
	/usr/local/go/src/math/rand/rand.go:103 +0x2b
github.com/spacemeshos/go-spacemesh/rand.Int(0xbf77ee4cc70c8e34)
	/go/src/github.com/spacemeshos/go-spacemesh/rand/rand.go:39 +0x2d
github.com/spacemeshos/go-spacemesh/p2p.(*swarm).sendMessageImpl(0xc0001c0480, 0xf7b940, 0xc003f40a60, 0xe542f1, 0xd, 0xf752e0, 0xc004907100, 0xbff34d258dd3db, 0x340223d47)
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/swarm.go:369 +0x767
github.com/spacemeshos/go-spacemesh/p2p.(*swarm).SendMessage(0xc0001c0480, 0xf7b940, 0xc003f40a60, 0xe542f1, 0xd, 0xc005bf0800, 0x1750, 0x1750, 0xff8e31fdc1e6c3e7, 0x11fc970ce6e50a)
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/swarm.go:308 +0xc6
github.com/spacemeshos/go-spacemesh/p2p/gossip.(*Protocol).propagateMessage.func1(0xc0001780c0, 0xe542f1, 0xd, 0xc005bf0800, 0x1750, 0x1750, 0x21d518a1a3379783, 0xc009bc20, 0xc007dedff0, 0xc0086d5010, ...)
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/gossip/protocol.go:123 +0xa4
created by github.com/spacemeshos/go-spacemesh/p2p/gossip.(*Protocol).propagateMessage
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/gossip/protocol.go:121 +0x3b0
       	t  N	00000.defaultLogger
new messages
Please add this to your branches, so we know the actual ATX size:
see len(buf) in the end
b.log.Event().Info("atx published!", log.AtxId(atx.ShortString()), log.String("prev_atx_id", atx.PrevATXId.ShortString()),
   log.String("post_atx_id", atx.PositioningAtx.ShortString()), log.LayerId(uint64(atx.PubLayerIdx)), log.EpochId(uint64(atx.PubLayerIdx.GetEpoch(b.layersPerEpoch))),
   log.Uint32("active_set", atx.ActiveSetSize), log.String("miner", b.nodeId.Key[:5]), log.Int("view", len(atx.View)), log.Int("atx_size", len(buf)))

**Comment by gavraz** [comment]
The solution, for now, is simply to use it appropriately. Just removed the additional call to rand.Seed.
