### ISSUE TITLE
Panic after stopping and starting a node

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1756]
Re opening for tracking because I can't find the previous issue. Repo:
1. Start node and sync.
2. Stop it and start again.

Result: in some cases go-spacemesh will panic, failing to load blocks from the db.

Expected: be able to sync to tip.

Will add log file next time I get it - happened 3 times for me today.

**Comment by avive** [comment]
Here's a log entry:
```
26dc4494d899d347a5fb82f02328184bda48491cError: Command failed: /Users/avive/dev/smapp/node/mac/go-spacemesh --grpc-server --json-server --tcp-port 7555 -d ~/spacemeshtestdata/ > /Users/avive/Documents/spacemesh-log.txt
panic: block 674f6 from layer 148 has no explicit voting, something went wrong 

goroutine 279 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00011b600, 0x0, 0x0, 0x0)
	/Users/avive/dev/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x546
go.uber.org/zap.(*SugaredLogger).log(0xc0000e8328, 0x604, 0xc0055a6190, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/avive/dev/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/Users/avive/dev/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0000b05a0, 0xc0000e8328, 0xc0055a6190, 0x48, 0x0, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/log/zap.go:42 +0x14a
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x9e87fe380c6c4f67, 0xbebc923141bec67c, 0xc0553a5887)
	/Users/avive/dev/go-spacemesh/tortoise/ninja_tortoise.go:444 +0x9f2
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc00054b6b0, 0xc004204be0)
	/Users/avive/dev/go-spacemesh/tortoise/ninja_tortoise.go:566 +0x71d
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc0052c6260, 0xc004204be0, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/tortoise/algorithm.go:54 +0xc8
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc0005622c0, 0xc004204be0)
	/Users/avive/dev/go-spacemesh/mesh/mesh.go:201 +0xf9
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleNotSynced(0xc000562420, 0x95)
	/Users/avive/dev/go-spacemesh/sync/syncer.go:355 +0xca
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise(0xc000562420)
	/Users/avive/dev/go-spacemesh/sync/syncer.go:318 +0x448
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getSyncRoutine.func1()
	/Users/avive/dev/go-spacemesh/sync/syncer.go:211 +0x6d
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
	/Users/avive/dev/go-spacemesh/sync/syncer.go:232 +0x234

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: '/Users/avive/dev/smapp/node/mac/go-spacemesh --grpc-server --json-server --tcp-port 7555 -d ~/spacemeshtestdata/ > /Users/avive/Documents/spacemesh-log.txt'
}
```

**Comment by avive** [comment]
this happens every time after I stop a node (synced or not) and starting it again. Here's another log:
```
2020-01-30T11:17:44.495+0200	INFO	64d7c.mesh         	Validate layer 166	{"node_id": "64d7c"}
2020-01-30T11:17:44.495+0200	INFO	64d7c.trtl         	Tortoise update tables	{"node_id": "64d7c", "layer_id": 166, "n_blocks": 30}
2020-01-30T11:17:44.807+0200	INFO	64d7c.trtl         	found minimal good layer 165, 3423575759	{"node_id": "64d7c"}
2020-01-30T11:17:44.854+0200	ERROR	64d7c.trtl         	Fatal: goroutine panicked. Stacktrace: goroutine 228 [running]:
runtime/debug.Stack(0x52ea5a0, 0x4aa5380, 0xc0063e05b0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000162c00, 0xc00058c350, 0xc0001941e0, 0x48, 0x0, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/log/zap.go:41 +0x26
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x6a93c723bce8e4c4, 0x2996edb004ab359c, 0xc0087688a4)
	/Users/avive/dev/go-spacemesh/tortoise/ninja_tortoise.go:444 +0x9f2
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc0001d2330, 0xc0055c65e0)
	/Users/avive/dev/go-spacemesh/tortoise/ninja_tortoise.go:566 +0x71d
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc0051b3580, 0xc0055c65e0, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/tortoise/algorithm.go:54 +0xc8
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc0001106e0, 0xc0055c65e0)
	/Users/avive/dev/go-spacemesh/mesh/mesh.go:201 +0xf9
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).GetAndValidateLayer(0xc000110840, 0xa6, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/sync/syncer.go:793 +0xf8
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise(0xc000110840)
	/Users/avive/dev/go-spacemesh/sync/syncer.go:311 +0x2eb
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getSyncRoutine.func1()
	/Users/avive/dev/go-spacemesh/sync/syncer.go:211 +0x6d
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
	/Users/avive/dev/go-spacemesh/sync/syncer.go:226 +0x24f
	{"node_id": "64d7c"}
2020-01-30T11:17:44.854+0200	PANIC	64d7c.trtl         	block c4e4e from layer 165 has no explicit voting, something went wrong 	{"node_id": "64d7c"}
```

**Comment by avive** [comment]
Here's the full log of the last instance - you can see that the node was gracefully shut-down before starting again:
```
2020-01-30T11:16:54.109+0200	INFO	64d7c.app          	64d7cdcac6a076f68c3d24f59231e55e01a70f3971836fa8b126af15b75c5c57 closing mesh	{"node_id": "64d7c"}
2020-01-30T11:16:54.110+0200	INFO	64d7c.meshDb       	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.111+0200	INFO	64d7c.meshDb       	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.111+0200	INFO	64d7c.meshDb       	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.112+0200	INFO	64d7c.meshDb       	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.112+0200	INFO	64d7c.meshDb       	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.112+0200	INFO	64d7c.meshDb       	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.113+0200	INFO	64d7c.stateDbStore 	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.113+0200	INFO	64d7c.atxDbStore   	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.114+0200	INFO	64d7c.poetDbStore  	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.114+0200	INFO	64d7c.stateDbStore 	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.115+0200	INFO	64d7c.store        	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.115+0200	INFO	64d7c.appliedTxs   	Database closed	{"node_id": "64d7c"}
2020-01-30T11:16:54.115+0200	INFO	00000.defaultLogger	App Cleanup completed


2020-01-30T11:17:43.234+0200	INFO	00000.defaultLogger	App version: 0.0.1. Git: develop - 6cdace92cfea51e1a16577b9ff8341dd304426fd . Go Version: go1.13.5. OS: darwin-amd64 
2020-01-30T11:17:43.234+0200	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
2020-01-30T11:17:43.474+0200	INFO	00000.defaultLogger	System clock synchronized with ntp. drift: -55.157611ms
2020-01-30T11:17:43.475+0200	INFO	00000.defaultLogger	Starting Spacemesh	{"event": true}
2020-01-30T11:17:43.475+0200	INFO	00000.defaultLogger	Initializing P2P services
2020-01-30T11:17:43.477+0200	INFO	00000.defaultLogger	>>>> Creating node identity from filesystem existing key 6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg
2020-01-30T11:17:43.477+0200	INFO	6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg	Local node identity >> 6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg
2020-01-30T11:17:43.493+0200	INFO	00000.defaultLogger	Saved node information. NodeID 6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg
2020-01-30T11:17:43.500+0200	INFO	00000.defaultLogger	Loaded 14 addresses from file '/Users/avive/spacemesh/peers.json'
2020-01-30T11:17:43.505+0200	INFO	00000.defaultLogger	Loaded identity from file ('/Users/avive/post/data/64d7cdcac6a076f68c3d24f59231e55e01a70f3971836fa8b126af15b75c5c57/key.bin')
2020-01-30T11:17:43.505+0200	INFO	00000.defaultLogger	connecting to POET on IP 35.231.54.161:50002
2020-01-30T11:17:43.859+0200	INFO	64d7c.stateDbStore 	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:43.861+0200	INFO	clock	starting global clock now=2020-01-30 11:17:43.859737 +0200 IST m=+0.682009241 genesis=2020-01-29 19:22:58 +0000 +0000
2020-01-30T11:17:43.861+0200	INFO	clock	global clock going to sleep before next layer	{"diff": "14.138786s", "next_layer": 167}
2020-01-30T11:17:43.908+0200	INFO	64d7c.atxDbStore   	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:43.974+0200	INFO	64d7c.poetDbStore  	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.016+0200	INFO	64d7c.stateDbStore 	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.061+0200	INFO	64d7c.store        	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.097+0200	INFO	64d7c.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.144+0200	INFO	64d7c.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.198+0200	INFO	64d7c.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.249+0200	INFO	64d7c.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.295+0200	INFO	64d7c.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.353+0200	INFO	64d7c.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.397+0200	INFO	64d7c.appliedTxs   	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "64d7c"}
2020-01-30T11:17:44.445+0200	INFO	64d7c.meshDb       	found data to recover on disc	{"node_id": "64d7c"}
2020-01-30T11:17:44.485+0200	INFO	64d7c.trtl         	recovered tortoise from disc	{"node_id": "64d7c"}
2020-01-30T11:17:44.486+0200	INFO	64d7c.state        	reverted, new root 7575ab71196fb7ac7f86cc4dcbf233a27f8855d09fbc4e41f1f27e1d4a7a7437	{"node_id": "64d7c"}
2020-01-30T11:17:44.486+0200	INFO	64d7c.state        	reverted	{"node_id": "64d7c", "root_hash": "0x7575ab71196fb7ac7f86cc4dcbf233a27f8855d09fbc4e41f1f27e1d4a7a7437"}
2020-01-30T11:17:44.486+0200	INFO	64d7c.mesh         	recovered mesh from disk	{"node_id": "64d7c", "latest_layer": 167, "validated_layer": 165, "layer_hash": "c35448f04325d020427708567f02c577e353976163467d7494a9108509437ee1"}
2020-01-30T11:17:44.486+0200	INFO	00000.defaultLogger	subscribed to channel
2020-01-30T11:17:44.487+0200	INFO	00000.defaultLogger	subscribed to channel
2020-01-30T11:17:44.488+0200	INFO	00000.defaultLogger	subscribed to channel
2020-01-30T11:17:44.489+0200	INFO	64d7c.app          	Genesis account created: 0x1, Balance: %!s(uint64=10000)	{"node_id": "64d7c"}
2020-01-30T11:17:44.489+0200	INFO	64d7c.app          	Genesis account created: 0x7be017a967db77fd10ac7c891b3d6d946dea7e3e14756e2f0f9e09b9663f0d9c, Balance: %!s(uint64=10000)	{"node_id": "64d7c"}
2020-01-30T11:17:44.489+0200	INFO	64d7c.app          	Genesis account created: 0x22a31a84ab876f82fcafba86e77910b4419a4ee0f1d5483d7dd3b5b6b6922ee9, Balance: %!s(uint64=10000)	{"node_id": "64d7c"}
2020-01-30T11:17:44.490+0200	WARN	64d7c.meshDb       	block already exist in database	{"node_id": "64d7c", "block_id": "a9f89"}
2020-01-30T11:17:44.490+0200	WARN	64d7c.mesh         	failed to add block a9f89  block already exist in database	{"node_id": "64d7c"}
2020-01-30T11:17:44.491+0200	INFO	64d7c.hare         	Starting HARE_PROTOCOL	{"node_id": "64d7c"}
2020-01-30T11:17:44.491+0200	INFO	64d7c.sync         	start synchronize	{"node_id": "64d7c"}
2020-01-30T11:17:44.491+0200	INFO	64d7c.sync         	Node is synced. Going to validate layer	{"node_id": "64d7c", "layer_id": 166}
2020-01-30T11:17:44.491+0200	INFO	64d7c.blockBuilder 	start listening for atxs	{"node_id": "64d7c"}
2020-01-30T11:17:44.491+0200	INFO	64d7c.blockBuilder 	start listening for txs	{"node_id": "64d7c"}
2020-01-30T11:17:44.492+0200	INFO	00000.defaultLogger	Manual post init
2020-01-30T11:17:44.492+0200	INFO	ticker	started notifying
2020-01-30T11:17:44.492+0200	INFO	00000.defaultLogger	challenge not loaded: leveldb: not found
2020-01-30T11:17:44.492+0200	INFO	6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg	Started TCP server listening for connections on tcp:[::]:7555
2020-01-30T11:17:44.492+0200	INFO	6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg	Started UDP server listening for messages on udp:[::]:7555
2020-01-30T11:17:44.492+0200	INFO	00000.defaultLogger	App started.
2020-01-30T11:17:44.492+0200	INFO	6tSuUFAaYEnmK3wZ6nZoUMxgquYz4DeHkiKcWPdHDMdg	Bootstrap: starting with 14 sized table
2020-01-30T11:17:44.493+0200	INFO	00000.defaultLogger	grpc API listening on port 9091
2020-01-30T11:17:44.494+0200	INFO	00000.defaultLogger	json API listening on port 9090
2020-01-30T11:17:44.495+0200	INFO	64d7c.mesh         	Validate layer 166	{"node_id": "64d7c"}
2020-01-30T11:17:44.495+0200	INFO	64d7c.trtl         	Tortoise update tables	{"node_id": "64d7c", "layer_id": 166, "n_blocks": 30}
2020-01-30T11:17:44.807+0200	INFO	64d7c.trtl         	found minimal good layer 165, 3423575759	{"node_id": "64d7c"}
2020-01-30T11:17:44.854+0200	ERROR	64d7c.trtl         	Fatal: goroutine panicked. Stacktrace: goroutine 228 [running]:
runtime/debug.Stack(0x52ea5a0, 0x4aa5380, 0xc0063e05b0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000162c00, 0xc00058c350, 0xc0001941e0, 0x48, 0x0, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/log/zap.go:41 +0x26
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x6a93c723bce8e4c4, 0x2996edb004ab359c, 0xc0087688a4)
	/Users/avive/dev/go-spacemesh/tortoise/ninja_tortoise.go:444 +0x9f2
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc0001d2330, 0xc0055c65e0)
	/Users/avive/dev/go-spacemesh/tortoise/ninja_tortoise.go:566 +0x71d
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc0051b3580, 0xc0055c65e0, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/tortoise/algorithm.go:54 +0xc8
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc0001106e0, 0xc0055c65e0)
	/Users/avive/dev/go-spacemesh/mesh/mesh.go:201 +0xf9
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).GetAndValidateLayer(0xc000110840, 0xa6, 0x0, 0x0)
	/Users/avive/dev/go-spacemesh/sync/syncer.go:793 +0xf8
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).Synchronise(0xc000110840)
	/Users/avive/dev/go-spacemesh/sync/syncer.go:311 +0x2eb
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getSyncRoutine.func1()
	/Users/avive/dev/go-spacemesh/sync/syncer.go:211 +0x6d
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
	/Users/avive/dev/go-spacemesh/sync/syncer.go:226 +0x24f
	{"node_id": "64d7c"}
2020-01-30T11:17:44.854+0200	PANIC	64d7c.trtl         	block c4e4e from layer 165 has no explicit voting, something went wrong 	{"node_id": "64d7c"}
```

**Comment by avive** [comment]
Might be a dupe of #1671
