### ISSUE TITLE
Unhandled error(grpc request)

### ISSUE THREAD

**Issue by ghost** [spacemeshos/go-spacemesh#1901]
## Description
Accidentally discovered that erroneously transmitted data kills the node process. 

## Steps To Reproduce
1. `curl http://localhost:9090/v1/accounttxs -H "Content-Type: application/json" -d '{"address":"0xafed9a1c17ca7eaa7a6795dbc7bee1b1d992c7ba"}'`
2. It will kill spacemesh process

## Expected Behavior
Correct error handling

## Environment
Please complete the following information:
 - OS: GNU/Linux Ubuntu 18.04
 
 - Node Version: 0.19.5
 

## Additional Resources 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbf75c0]

goroutine 161490 [running]:
github.com/spacemeshos/go-spacemesh/api.SpacemeshGrpcService.GetAccountTxs(0xc00026f8c0, 0x2383, 0x1063aa0, 0xc00054e000, 0x7f6349ac4558, 0xc0000c6780, 0x1077220, 0xc00035a000, 0xc0002a6330, 0x10632e0, ...)
        /home/parallels/dev/go-spacemesh/api/grpc_server.go:392 +0xb0
github.com/spacemeshos/go-spacemesh/api/pb._SpacemeshService_GetAccountTxs_Handler(0xecdb20, 0xc051ad0d00, 0x1069ca0, 0xc052640540, 0xc051cb6420, 0x0, 0x1069ca0, 0xc052640540, 0x0, 0x0)
        /home/parallels/dev/go-spacemesh/api/pb/api.pb.go:1717 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00026f8c0, 0x1075120, 0xc01086d200, 0xc00a9c5500, 0xc051abf650, 0x18b8550, 0x0, 0x0, 0x0)
        /home/parallels/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00026f8c0, 0x1075120, 0xc01086d200, 0xc00a9c5500, 0x0)
        /home/parallels/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc03ce61690, 0xc00026f8c0, 0x1075120, 0xc01086d200, 0xc00a9c5500)
        /home/parallels/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/parallels/go/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:708 +0xa1
```

**Comment by moshababo** [comment]
Thanks for reporting!
Will be fixed soon.
