### ISSUE TITLE
"Fatal: goroutine panicked. Stacktrace: goroutine 1 [running]" exception

### ISSUE THREAD

**Issue by sl-he** [spacemeshos/go-spacemesh#1989]
## Description
I just run my node with last snapshot (https://github.com/spacemeshos/go-spacemesh/tree/9e60bf9fc6a714b9fcbb925fa2714349e5378af6)

## Steps To Reproduce
1. Just run node with command /home/user/source/go-spacemesh/build/go-spacemesh --grpc-server --json-server --tcp-port 7153 --config /home/user/source/go-spacemesh/build/tn01.toml -d /home/user/source/go-spacemesh/build/sm_data --post-datadir /home/user/source/go-spacemesh/build/post_data --start-mining --coinbase MY_ADDRESS
2. See error

## Environment
Please complete the following information:
 - OS: Ubuntu 18.04.3 LTS in CLI mode
 - Node Version: 0.1.6+9e60bf9fc6a714b9fcbb925fa2714349e5378af6

## Additional Resources 
```
2020-04-14T20:37:07.310Z#011INFO#01100000.defaultLogger#011App version: 0.1.6. Git: develop - 9e60bf9fc6a714b9fcbb925fa2714349e5378af6 . Go Version: go1.14. OS: linux-amd64
2020-04-14T20:37:07.310Z#011INFO#01100000.defaultLogger#011Welcome to Spacemesh. Spacemesh full node is starting...
2020-04-14T20:37:07.450Z#011INFO#01100000.defaultLogger#011ntp check from server time-a-wwv.nist.gov, drift: -64.21916ms, start_check: 2020-04-14 20:37:07.314334229 +0000 UTC, latency: 78.698µs, rsp: 2020-04-14 20:37:07.37851404 +0000 UTC
2020-04-14T20:37:07.468Z#011INFO#01100000.defaultLogger#011ntp check from server time3.google.com, drift: -5.554427ms, start_check: 2020-04-14 20:37:07.452028208 +0000 UTC, latency: 47.365µs, rsp: 2020-04-14 20:37:07.457558953 +0000 UTC
2020-04-14T20:37:07.486Z#011INFO#01100000.defaultLogger#011ntp check from server time.google.com, drift: -5.841607ms, start_check: 2020-04-14 20:37:07.469424605 +0000 UTC, latency: 54.12µs, rsp: 2020-04-14 20:37:07.475239152 +0000 UTC
2020-04-14T20:37:07.506Z#011INFO#01100000.defaultLogger#011ntp check from server time1.google.com, drift: -7.160302ms, start_check: 2020-04-14 20:37:07.489117441 +0000 UTC, latency: 38.991µs, rsp: 2020-04-14 20:37:07.496258248 +0000 UTC
2020-04-14T20:37:07.643Z#011INFO#01100000.defaultLogger#011ntp check from server time-b-wwv.nist.gov, drift: -66.132736ms, start_check: 2020-04-14 20:37:07.507841864 +0000 UTC, latency: 51.799µs, rsp: 2020-04-14 20:37:07.573948701 +0000 UTC
2020-04-14T20:37:07.643Z#011INFO#01100000.defaultLogger#011System clock synchronized with ntp. drift: -25.740356ms
2020-04-14T20:37:07.643Z#011INFO#01100000.defaultLogger#011Starting Spacemesh#011{"data-dir": "/home/user/source/go-spacemesh/build/sm_data", "post-dir": "/home/user/source/go-spacemesh/build/post_data"}
2020-04-14T20:37:07.644Z#011INFO#01100000.defaultLogger#011Loaded identity from file ('/home/user/source/go-spacemesh/build/post_data/58fa6bc8214d5eb3c0ff22a1c9ed2a7ce53a459027b1629d4dc0aee302112f8b/key.bin')
2020-04-14T20:37:07.682Z#011INFO#011clock#011starting global clock now=2020-04-14 20:37:07.682312616 +0000 UTC m=+0.401235715 genesis=2020-03-19 18:18:42 +0000 UTC
2020-04-14T20:37:07.682Z#011INFO#011clock#011global clock going to sleep before next layer#011{"diff": "1m34.317501618s", "next_layer": 7516}
2020-04-14T20:37:07.682Z#011INFO#01100000.defaultLogger#011Initializing P2P services
2020-04-14T20:37:07.682Z#011INFO#01158fa6.p2p          #011Local node identity >> 8kBqjjpstAV9jgjQk9sxU75FBsj7PtuwTG71sLvw3xWn
2020-04-14T20:37:07.694Z#011INFO#01100000.defaultLogger#011Saved p2p node information (/home/user/source/go-spacemesh/build/sm_data/p2p/nodes/8kBqjjpstAV9jgjQk9sxU75FBsj7PtuwTG71sLvw3xWn/id.json),  Identity - 8kBqjjpstAV9jgjQk9sxU75FBsj7PtuwTG71sLvw3xWn
2020-04-14T20:37:07.708Z#011INFO#01100000.defaultLogger#011Loaded 154 addresses from file '/home/user/source/go-spacemesh/build/sm_data/p2p/peers.json'
2020-04-14T20:37:07.709Z#011INFO#01158fa6.stateDbStore #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.719Z#011INFO#01158fa6.atxDbStore   #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.735Z#011INFO#01158fa6.poetDbStore  #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.772Z#011INFO#01158fa6.stateDbStore #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.790Z#011INFO#01158fa6.store        #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.801Z#011INFO#01158fa6.meshDb       #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.846Z#011INFO#01158fa6.meshDb       #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.874Z#011INFO#01158fa6.meshDb       #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.901Z#011INFO#01158fa6.meshDb       #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.919Z#011INFO#01158fa6.meshDb       #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.929Z#011INFO#01158fa6.meshDb       #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.940Z#011INFO#01158fa6.appliedTxs   #011Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)#011{"node_id": "58fa6"}
2020-04-14T20:37:07.960Z#011INFO#01100000.defaultLogger#011started processor with state root 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
2020-04-14T20:37:07.976Z#011INFO#01158fa6.meshDb       #011found data to recover on disc#011{"node_id": "58fa6"}
2020-04-14T20:37:08.625Z#011INFO#01158fa6.trtl         #011recovered tortoise from disc#011{"node_id": "58fa6"}
2020-04-14T20:37:08.625Z#011ERROR#01158fa6.mesh         #011Fatal: goroutine panicked. Stacktrace: goroutine 1 [running]:
runtime/debug.Stack(0xc0000a7a00, 0xf3d5a0, 0xc0005c00c0)
#011/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000304c60, 0xc00028bab8, 0xc00028baa8, 0xf156b3, 0x25, 0xc0005c01c0, 0x1, 0x1)
#011/root/source/go-spacemesh/log/zap.go:46 +0x26
github.com/spacemeshos/go-spacemesh/mesh.NewRecoveredMesh(0xc0000d16b0, 0x108a900, 0xc0001aa000, 0xc000288680, 0x7fdd32bcc340, 0xc00028baa0, 0x10717c0, 0xc00090a450, 0x1071780, 0xc000288e00, ...)
#011/root/source/go-spacemesh/mesh/mesh.go:146 +0x3f9
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).initServices(0xc0001fe480, 0xc0005af480, 0x40, 0xc0003aa300, 0xc0, 0xc0, 0x1090bc0, 0xc0000de500, 0x7fff6924de51, 0x2c, ...)
#011/root/source/go-spacemesh/cmd/node/node.go:506 +0x18b7
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc0001fe480, 0x191a260, 0xc0001d4a90, 0x0, 0xd)
#011/root/source/go-spacemesh/cmd/node/node.go:888 +0xe2b
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x191a260, 0xc0001d4a90, 0x0, 0xd)
#011/root/source/go-spacemesh/cmd/node/node.go:93 +0x1f1
github.com/spf13/cobra.(*Command).execute(0x191a260, 0xc0000c0010, 0xd, 0xd, 0x191a260, 0xc0000c0010)
#011/root/work/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x191a260, 0xc000000180, 0xc0001cff78, 0x40769f)
#011/root/work/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
#011/root/work/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
#011/root/source/go-spacemesh/main.go:23 +0xac
#011{"node_id": "58fa6"}
2020-04-14T20:37:08.625Z#011PANIC#01158fa6.mesh         #011could not recover processed layer: leveldb: not found#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01100000.defaultLogger#011App Cleanup starting...
2020-04-14T20:37:08.626Z#011INFO#01158fa6.stateDbStore #011Database closed#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01158fa6.atxDbStore   #011Database closed#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01158fa6.poetDbStore  #011Database closed#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01158fa6.stateDbStore #011Database closed#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01158fa6.store        #011Database closed#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01158fa6.appliedTxs   #011Database closed#011{"node_id": "58fa6"}
2020-04-14T20:37:08.626Z#011INFO#01100000.defaultLogger#011App Cleanup completed
panic: could not recover processed layer: leveldb: not found
goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000d1550, 0x0, 0x0, 0x0)
#011/root/work/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x545
go.uber.org/zap.(*SugaredLogger).log(0xc00028bab8, 0x604, 0xf156b3, 0x25, 0xc0005c01c0, 0x1, 0x1, 0x0, 0x0, 0x0)
#011/root/work/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panicf(...)
#011/root/work/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000304c60, 0xc00028bab8, 0xc00028baa8, 0xf156b3, 0x25, 0xc0005c01c0, 0x1, 0x1)
#011/root/source/go-spacemesh/log/zap.go:47 +0x149
github.com/spacemeshos/go-spacemesh/mesh.NewRecoveredMesh(0xc0000d16b0, 0x108a900, 0xc0001aa000, 0xc000288680, 0x7fdd32bcc340, 0xc00028baa0, 0x10717c0, 0xc00090a450, 0x1071780, 0xc000288e00, ...)
#011/root/source/go-spacemesh/mesh/mesh.go:146 +0x3f9
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).initServices(0xc0001fe480, 0xc0005af480, 0x40, 0xc0003aa300, 0xc0, 0xc0, 0x1090bc0, 0xc0000de500, 0x7fff6924de51, 0x2c, ...)
#011/root/source/go-spacemesh/cmd/node/node.go:506 +0x18b7
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc0001fe480, 0x191a260, 0xc0001d4a90, 0x0, 0xd)
#011/root/source/go-spacemesh/cmd/node/node.go:888 +0xe2b
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x191a260, 0xc0001d4a90, 0x0, 0xd)
#011/root/source/go-spacemesh/cmd/node/node.go:93 +0x1f1
github.com/spf13/cobra.(*Command).execute(0x191a260, 0xc0000c0010, 0xd, 0xd, 0x191a260, 0xc0000c0010)
#011/root/work/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x191a260, 0xc000000180, 0xc0001cff78, 0x40769f)
#011/root/work/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
#011/root/work/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
#011/root/source/go-spacemesh/main.go:23 +0xac
```

**Comment by avive** [comment]
Thanks for the nice bug report and stack trace. Curious what happens if you delete /home/user/source/go-spacemesh/build/sm_data and run again - do you get the same error or no error?

**Comment by sl-he** [comment]
Now I updated the version to 0.1.9 and I no longer see this error...

**Comment by avive** [comment]
After updating - did you run with the same data folder using existing data or did you start with a new empty data folder?

**Comment by sl-he** [comment]
I run with the same data folder using existing data

**Comment by antonlerner** [comment]
crashed component will be replaced by #1856
