### ISSUE TITLE
Sync shutdown panic

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1996]
## Description

Looks similar to #1774 but different enough that I'm opening this.

```
2020-04-19T18:32:12.324-0400    INFO    4c292.mesh              added block to database         {"node_id": "4c292", "block_id": "c5f5c", "layer_id": 6266}
2020-04-19T18:32:12.324-0400    INFO    4c292.sync         .blockFetchQueue     finished block c5f5c, valid     {"node_id": "4c292"}
2020-04-19T18:32:12.324-0400    INFO    4c292.sync         .blockFetchQueue     pending done for c5f5c  {"node_id": "4c292"}
2020-04-19T18:32:12.325-0400    INFO    4c292.sync         .blockFetchQueue     invalidated c5f5c true  {"node_id": "4c292"}
2020-04-19T18:32:12.325-0400    INFO    4c292.sync              layer 6266 done {"node_id": "4c292"}
2020-04-19T18:32:12.325-0400    INFO    4c292.mesh              Validate layer 6266     {"node_id": "4c292"}
2020-04-19T18:32:12.325-0400    INFO    4c292.trtl              Tortoise update tables  {"node_id": "4c292", "layer_id": 6266, "n_blocks": 35}
2020-04-19T18:32:12.448-0400    ERROR   4c292.p2p          .udpnet              Listen UDP error, stopping server      {"P2PID": "EDYaxmMFXygBi8DPJHPbFRgdxpHkgxHNzjyJj2NepLoo", "error": "read udp [::]:7153: use of closed network connection"}
2020-04-19T18:32:12.448-0400    INFO    4c292.app               4c292347ab008e6fc1675548f68e17961595ec8b49e7ffb42e488cdbe919d68b closing mesh                                      {"node_id": "4c292"}
2020-04-19T18:32:12.456-0400    INFO    4c292.trtl              found minimal good layer 6265, 976337682        {"node_id": "4c292"}
2020-04-19T18:32:12.552-0400    INFO    4c292.meshDb            Database closed {"node_id": "4c292"}
2020-04-19T18:32:12.581-0400    ERROR   4c292.trtl              Fatal: goroutine panicked. Stacktrace: goroutine 891968 [running]:
runtime/debug.Stack(0x2, 0x2, 0x10c89e0)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0001e8840, 0xc000138298, 0xc000138288, 0xf7c469, 0x22, 0x0, 0x0, 0x0)
        C:/dev/go-spacemesh/log/zap.go:44 +0x2d
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x6779e9b088492e4b, 0x210dca19b87fc0f2, 0xc046d00d6b)
        C:/dev/go-spacemesh/tortoise/ninja_tortoise.go:450 +0x89e
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc0006078c0, 0xc0096d1600)
        C:/dev/go-spacemesh/tortoise/ninja_tortoise.go:566 +0x6d7
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc0061bfe80, 0xc0096d1600, 0x0, 0x0)
        C:/dev/go-spacemesh/tortoise/algorithm.go:56 +0xcf
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc000608000, 0xc0096d1600)
        C:/dev/go-spacemesh/mesh/mesh.go:212 +0x100
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleNotSynced(0xc0000777c0, 0x1785)
        C:/dev/go-spacemesh/sync/syncer.go:344 +0xd1
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc0000777c0)
        C:/dev/go-spacemesh/sync/syncer.go:301 +0x550
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
        C:/dev/go-spacemesh/sync/syncer.go:258 +0x120
        {"node_id": "4c292"}
2020-04-19T18:32:12.581-0400    PANIC   4c292.trtl              could not retrieve layer block ids      {"node_id": "4c292"}
2020-04-19T18:32:12.589-0400    INFO    4c292.sync              close synchronize, Node is out of Sync latest: 6266, maxSynced 8979                                                {"node_id": "4c292"}
```

It happened after the node shutdown due to a time sync issue:

```
2020-04-19T18:32:11.323-0400    INFO    00000.defaultLogger     ntp check from server 0.pool.ntp.org, drift: -56.537206783s, start_check: 2020-04-19 22:32:10.1935776 +0000 UTC, latency: 1.0512666s, rsp: 2020-04-19 22:33:06.205151083 +0000 UTC
2020-04-19T18:32:11.323-0400    INFO    00000.defaultLogger     ntp check from server time1.google.com, drift: -56.538565236s, start_check: 2020-04-19 22:32:10.1942096 +0000 UTC, latency: 1.0503169s, rsp: 2020-04-19 22:33:06.207616386 +0000 UTC
2020-04-19T18:32:11.526-0400    ERROR   4c292.app               System time couldn't synchronize System clock is -56.414479245s away from NTP servers. please synchronize your OS  {"node_id": "4c292"}
```

## Steps To Reproduce

Run smapp 0.0.7 on Windows and let your clock drift :)

## Environment
Please complete the following information:
 - OS: Windows 10
 - App Version: 0.0.7

**Comment by lrettig** [comment]
Aviv encountered the same issue in #1999 and posted a full log in case it's helpful: https://drive.google.com/open?id=1VCzT_UqgF2nM2k33TmDKF3UDQeSD3XqJ
