### ISSUE TITLE
Node crash on sync

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1999]
## Description
Node crashed while syncing the mesh.

## Steps To Reproduce
Run the app w/o any prior data (sync from scratch).

## Expected Behavior
Node not to crash and to finish syncing.

## Environment
Please complete the following information:
Windows 10 Home, Node v0.1.9, App 0.0.7 (release candidate)

## Additional Resources 
Complete logs: https://drive.google.com/open?id=1VCzT_UqgF2nM2k33TmDKF3UDQeSD3XqJ

**Comment by lrettig** [comment]
From the end of the logfile Aviv posted:

```
2020-04-20T23:06:24.645+0300	INFO	00000.defaultLogger	App version: 0.0.1. Git: develop - 238f9579d73804930e821a039bd61646cf150b7a . Go Version: go1.13.5. OS: windows-amd64 
2020-04-20T23:06:24.645+0300	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
2020-04-20T23:06:24.676+0300	INFO	00000.defaultLogger	ntp check from server 1.pool.ntp.org, drift: -104.941344ms, start_check: 2020-04-20 20:06:24.6648042 +0000 UTC, latency: 0s, rsp: 2020-04-20 20:06:24.769745544 +0000 UTC
2020-04-20T23:06:24.685+0300	INFO	00000.defaultLogger	ntp check from server 0.pool.ntp.org, drift: -103.939515ms, start_check: 2020-04-20 20:06:24.6727602 +0000 UTC, latency: 0s, rsp: 2020-04-20 20:06:24.776699715 +0000 UTC
2020-04-20T23:06:24.728+0300	INFO	00000.defaultLogger	ntp check from server time1.google.com, drift: -138.550645ms, start_check: 2020-04-20 20:06:24.6508233 +0000 UTC, latency: 0s, rsp: 2020-04-20 20:06:24.789373945 +0000 UTC
2020-04-20T23:06:24.733+0300	INFO	00000.defaultLogger	ntp check from server time.google.com, drift: -141.934517ms, start_check: 2020-04-20 20:06:24.6508233 +0000 UTC, latency: 0s, rsp: 2020-04-20 20:06:24.792757817 +0000 UTC
2020-04-20T23:06:24.739+0300	INFO	00000.defaultLogger	ntp check from server time.asia.apple.com, drift: -134.128059ms, start_check: 2020-04-20 20:06:24.6727602 +0000 UTC, latency: 0s, rsp: 2020-04-20 20:06:24.806888259 +0000 UTC
2020-04-20T23:06:24.739+0300	INFO	00000.defaultLogger	System clock synchronized with ntp. drift: -125.873349ms
2020-04-20T23:06:24.739+0300	INFO	00000.defaultLogger	Starting Spacemesh	{"data-dir": "C:\\Users\\Spacemesher\\AppData\\Roaming\\Spacemesh\\spacemeshtestdata", "post-dir": "C:\\Users\\Spacemesher\\Documents"}
2020-04-20T23:06:24.744+0300	INFO	00000.defaultLogger	Loaded identity from file ('C:\Users\Spacemesher\Documents\d07eb3120b554c6b14c9b42dbbfb9f8a60a3875f017ffc992a415646577b9310\key.bin')
2020-04-20T23:06:24.752+0300	INFO	00000.defaultLogger	Initializing P2P services
2020-04-20T23:06:24.752+0300	INFO	clock	starting global clock now=2020-04-20 23:06:24.7527361 +0300 IDT m=+0.136921101 genesis=2020-03-19 18:18:42 +0000 +0000
2020-04-20T23:06:24.752+0300	INFO	clock	global clock going to sleep before next layer	{"diff": "2m17.2472639s", "next_layer": 9238}
2020-04-20T23:06:24.753+0300	INFO	d07eb.p2p          	Local node identity >> Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat
2020-04-20T23:06:24.759+0300	INFO	00000.defaultLogger	Saved p2p node information (C:\Users\Spacemesher\AppData\Roaming\Spacemesh\spacemeshtestdata\p2p\nodes\Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat\id.json),  Identity - Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat
2020-04-20T23:06:24.770+0300	INFO	00000.defaultLogger	Loaded 476 addresses from file 'C:\Users\Spacemesher\AppData\Roaming\Spacemesh\spacemeshtestdata\p2p\peers.json'
2020-04-20T23:06:24.770+0300	INFO	d07eb.stateDbStore 	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.781+0300	INFO	d07eb.atxDbStore   	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.792+0300	INFO	d07eb.poetDbStore  	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.800+0300	INFO	d07eb.stateDbStore 	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.807+0300	INFO	d07eb.store        	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.815+0300	INFO	d07eb.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.832+0300	INFO	d07eb.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.841+0300	INFO	d07eb.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.847+0300	INFO	d07eb.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.863+0300	INFO	d07eb.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.878+0300	INFO	d07eb.meshDb       	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.889+0300	INFO	d07eb.appliedTxs   	Allocated cache and file handles%!(EXTRA string=cache, int=16, string=handles, int=16)	{"node_id": "d07eb"}
2020-04-20T23:06:24.895+0300	INFO	00000.defaultLogger	started processor with state root 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
2020-04-20T23:06:24.895+0300	INFO	d07eb.meshDb       	found data to recover on disc	{"node_id": "d07eb"}
2020-04-20T23:06:25.113+0300	INFO	d07eb.trtl         	recovered tortoise from disc	{"node_id": "d07eb"}
2020-04-20T23:06:25.113+0300	INFO	d07eb.state        	reverted, new root 73ef07d8f81fe048af8b544f466faa72b765fa5ee5c2df8acd598adfbb8677ce	{"node_id": "d07eb"}
2020-04-20T23:06:25.113+0300	INFO	d07eb.state        	reverted	{"node_id": "d07eb", "root_hash": "0x73ef07d8f81fe048af8b544f466faa72b765fa5ee5c2df8acd598adfbb8677ce"}
2020-04-20T23:06:25.113+0300	INFO	d07eb.mesh         	recovered mesh from disc	{"node_id": "d07eb", "latest_layer": 1452, "validated_layer": 1451, "layer_hash": "32b1f50746f465fe33be4f27b89232149804c2b5495a0a7a8db8304dfb3b1912", "root_hash": "0x73ef07d8f81fe048af8b544f466faa72b765fa5ee5c2df8acd598adfbb8677ce"}
2020-04-20T23:06:25.114+0300	INFO	00000.defaultLogger	subscribed to channel
2020-04-20T23:06:25.114+0300	INFO	00000.defaultLogger	subscribed to channel
2020-04-20T23:06:25.114+0300	INFO	d07eb.hare         	Starting HARE_PROTOCOL	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.sync         	start synchronize	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.sync         	Node is out of sync setting gossip-synced to false and starting sync	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.sync         	syncing layer	{"node_id": "d07eb", "current_sync_layer": 1452, "last_ticked_layer": 9238}
2020-04-20T23:06:25.114+0300	INFO	d07eb.blockBuilder 	start listening for txs	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.blockBuilder 	start listening for atxs	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.sync         .peers        	now connected	{"node_id": "d07eb", "n_peers": 0}
2020-04-20T23:06:25.114+0300	INFO	d07eb.sync         	could not get layer 1452 from neighbors: no peers 	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.sync         	close synchronize, Node is out of Sync latest: 1452, maxSynced 9238	{"node_id": "d07eb"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.atxBuilder   	Starting PoST initialization	{"node_id": "d07eb", "datadir": "C:\\Users\\Spacemesher\\Documents", "space": "4294967296", "rewardAddress": "9ec197c105a35ea163ec564e066c963f3df98e8e"}
2020-04-20T23:06:25.114+0300	INFO	ticker	started notifying
2020-04-20T23:06:25.114+0300	INFO	00000.defaultLogger	challenge not loaded: leveldb: not found
2020-04-20T23:06:25.114+0300	INFO	d07eb.p2p          .tcpnet       	Started TCP server listening for connections on tcp:[::]:7153	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:25.114+0300	INFO	d07eb.p2p          .udpnet       	Started UDP server listening for messages on udp:[::]:7153	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:25.115+0300	INFO	d07eb.p2p          	Bootstrap: starting with 476 sized table	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:25.115+0300	INFO	00000.defaultLogger	App started.
2020-04-20T23:06:25.115+0300	INFO	00000.defaultLogger	grpc API listening on port 9091
2020-04-20T23:06:25.115+0300	INFO	d07eb.post         	execution: start executing 1 files, parallelism degree: 1
	{"node_id": "d07eb"}
2020-04-20T23:06:25.115+0300	INFO	00000.defaultLogger	json API listening on port 9090
2020-04-20T23:06:25.208+0300	WARN	d07eb.p2p          	Peer spacemesh://8wvx5NGw1G2JPrp2n6zsrVJpd7TUBBjSNTezVQeqiqPk@116.202.196.95:7152 didn't response to protocol queries - err:got pong with different public key	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:30.115+0300	WARN	d07eb.p2p          	Peer spacemesh://DrkJXXtAPs8PRkyeU3789fGvMko1HZU8kEnHhZQ8YD5V@141.226.37.55:7153 didn't response to protocol queries - err:ping timeouted	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:30.209+0300	WARN	d07eb.p2p          	Peer spacemesh://GJs4qK3FX2BVsUf1GvoX5unx5hVBLNZGvPzhqu9zZWoi@74.72.208.122:7590 didn't response to protocol queries - err:ping timeouted	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:30.454+0300	WARN	d07eb.p2p          	Peer spacemesh://DZ5Xy3EGWqgKJgtase4gvM6vC7eUoCUZStD3PRvnDdsg@95.165.154.226:7153 didn't response to protocol queries - err:ping timeouted	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:35.114+0300	INFO	d07eb.sync         	start synchronize	{"node_id": "d07eb"}
2020-04-20T23:06:35.114+0300	INFO	d07eb.sync         	Node is out of sync setting gossip-synced to false and starting sync	{"node_id": "d07eb"}
2020-04-20T23:06:35.114+0300	INFO	d07eb.sync         	syncing layer	{"node_id": "d07eb", "current_sync_layer": 1452, "last_ticked_layer": 9238}
2020-04-20T23:06:35.114+0300	INFO	d07eb.sync         .peers        	now connected	{"node_id": "d07eb", "n_peers": 0}
2020-04-20T23:06:35.114+0300	INFO	d07eb.sync         	could not get layer 1452 from neighbors: no peers 	{"node_id": "d07eb"}
2020-04-20T23:06:35.114+0300	INFO	d07eb.sync         	close synchronize, Node is out of Sync latest: 1452, maxSynced 9238	{"node_id": "d07eb"}
2020-04-20T23:06:35.117+0300	WARN	d07eb.p2p          	Peer spacemesh://9ZkgEaePxSPc2QAUCQP3PBkkJbnfLGyDUCrwB8vZk7xZ@77.139.178.2:7153 didn't response to protocol queries - err:ping timeouted	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:35.117+0300	INFO	d07eb.p2p          	Bootstrap : 1 try gave 59 results	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:35.117+0300	INFO	d07eb.p2p          	Stopping bootstrap, achieved 21 need 8	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:35.117+0300	INFO	d07eb.p2p          	discovery_bootstrap	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "event": true, "success": true, "size": 497, "time_elapsed": "10.0012677s"}
2020-04-20T23:06:35.117+0300	INFO	d07eb.p2p          	Neighborhood service started	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat"}
2020-04-20T23:06:35.184+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "9Ae88ZTstfeBUgnnSpjuwYW77aBfnNpmFwAUDEE1A2wj"}
2020-04-20T23:06:35.185+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "9Ae88ZTstfeBUgnnSpjuwYW77aBfnNpmFwAUDEE1A2wj"}
2020-04-20T23:06:35.205+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "BMDKoUFW1VkDUVwWdtzNBEa61xS3RtFoDPguJhqp7wYM"}
2020-04-20T23:06:35.205+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "BMDKoUFW1VkDUVwWdtzNBEa61xS3RtFoDPguJhqp7wYM"}
2020-04-20T23:06:35.264+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "828AsQC2mDAF8gJKHfmU5TbfTPcKkeYgkDD3X5taTJDk"}
2020-04-20T23:06:35.264+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "828AsQC2mDAF8gJKHfmU5TbfTPcKkeYgkDD3X5taTJDk"}
2020-04-20T23:06:35.271+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "Cj8DubGMnMGAUUQspZo3YjV1PR1qbJ4zgmAHgMpYMMVN"}
2020-04-20T23:06:35.271+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "Cj8DubGMnMGAUUQspZo3YjV1PR1qbJ4zgmAHgMpYMMVN"}
2020-04-20T23:06:35.352+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "FP9UMswPtbB7vpago58Ar7bNGmrnovHUe3KURjsQneXR"}
2020-04-20T23:06:35.352+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "FP9UMswPtbB7vpago58Ar7bNGmrnovHUe3KURjsQneXR"}
2020-04-20T23:06:35.407+0300	INFO	d07eb.p2p          .tcpnet       	connection_closed	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "id": "d9a832ad-95d2-4d1e-b99d-f57b7b045a85", "remote": "828AsQC2mDAF8gJKHfmU5TbfTPcKkeYgkDD3X5taTJDk", "error": "EOF"}
2020-04-20T23:06:35.407+0300	INFO	d07eb.p2p          .tcpnet       	connection_closed	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "id": "d9a832ad-95d2-4d1e-b99d-f57b7b045a85", "remote": "828AsQC2mDAF8gJKHfmU5TbfTPcKkeYgkDD3X5taTJDk"}
2020-04-20T23:06:35.407+0300	INFO	d07eb.p2p          	deleting peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "828AsQC2mDAF8gJKHfmU5TbfTPcKkeYgkDD3X5taTJDk"}
2020-04-20T23:06:35.440+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "HtXGTWsEhdeJkgTne4nc7sPqii9ETXwddSWaTwj1M4mf"}
2020-04-20T23:06:35.440+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "HtXGTWsEhdeJkgTne4nc7sPqii9ETXwddSWaTwj1M4mf"}
2020-04-20T23:06:35.455+0300	INFO	d07eb.p2p          .tcpnet       	new_connection	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "src": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "dst": "AEqs7p9SEjz2rD4te8XKwkwzsvAaiMZBg29yCnL69zPc"}
2020-04-20T23:06:35.455+0300	INFO	d07eb.p2p          	adding peer	{"P2PID": "Gj6woU8xNpX5iMMLWoH1dt49kdjibffeabH4Wu1KQKat", "peer": "AEqs7p9SEjz2rD4te8XKwkwzsvAaiMZBg29yCnL69zPc"}
2020-04-20T23:06:39.273+0300	INFO	00000.defaultLogger	GRPC GetInitProgress msg
2020-04-20T23:06:39.473+0300	INFO	00000.defaultLogger	GRPC GetStateRoot msg
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         	start synchronize	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         	Node is out of sync setting gossip-synced to false and starting sync	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         	syncing layer	{"node_id": "d07eb", "current_sync_layer": 1452, "last_ticked_layer": 9238}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peers        	now connected	{"node_id": "d07eb", "n_peers": 6}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peers        	now connected	{"node_id": "d07eb", "n_peers": 6}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peersWrkr    	send request Peer: HtXGTWsEhdeJkgTne4nc7sPqii9ETXwddSWaTwj1M4mf	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peersWrkr    	send request Peer: FP9UMswPtbB7vpago58Ar7bNGmrnovHUe3KURjsQneXR	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peersWrkr    	send request Peer: BMDKoUFW1VkDUVwWdtzNBEa61xS3RtFoDPguJhqp7wYM	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peersWrkr    	send request Peer: 9Ae88ZTstfeBUgnnSpjuwYW77aBfnNpmFwAUDEE1A2wj	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peersWrkr    	send request Peer: Cj8DubGMnMGAUUQspZo3YjV1PR1qbJ4zgmAHgMpYMMVN	{"node_id": "d07eb"}
2020-04-20T23:06:45.114+0300	INFO	d07eb.sync         .peersWrkr    	send request Peer: AEqs7p9SEjz2rD4te8XKwkwzsvAaiMZBg29yCnL69zPc	{"node_id": "d07eb"}
2020-04-20T23:06:45.396+0300	INFO	d07eb.sync         .peersWrkr    	Peer: BMDKoUFW1VkDUVwWdtzNBEa61xS3RtFoDPguJhqp7wYM responded	{"node_id": "d07eb"}
2020-04-20T23:06:45.411+0300	INFO	d07eb.sync         .peersWrkr    	Peer: FP9UMswPtbB7vpago58Ar7bNGmrnovHUe3KURjsQneXR responded	{"node_id": "d07eb"}
2020-04-20T23:06:45.500+0300	INFO	d07eb.sync         .peersWrkr    	Peer: HtXGTWsEhdeJkgTne4nc7sPqii9ETXwddSWaTwj1M4mf responded	{"node_id": "d07eb"}
2020-04-20T23:06:45.503+0300	INFO	d07eb.sync         .peersWrkr    	Peer: AEqs7p9SEjz2rD4te8XKwkwzsvAaiMZBg29yCnL69zPc responded	{"node_id": "d07eb"}
2020-04-20T23:06:45.508+0300	INFO	d07eb.sync         .peersWrkr    	Peer: 9Ae88ZTstfeBUgnnSpjuwYW77aBfnNpmFwAUDEE1A2wj responded	{"node_id": "d07eb"}
2020-04-20T23:06:45.990+0300	INFO	d07eb.sync         .peersWrkr    	Peer: Cj8DubGMnMGAUUQspZo3YjV1PR1qbJ4zgmAHgMpYMMVN responded	{"node_id": "d07eb"}
2020-04-20T23:06:45.991+0300	INFO	d07eb.sync         	send request Peer: BMDKoUFW1VkDUVwWdtzNBEa61xS3RtFoDPguJhqp7wYM	{"node_id": "d07eb"}
2020-04-20T23:06:46.056+0300	INFO	d07eb.sync         	Peer: BMDKoUFW1VkDUVwWdtzNBEa61xS3RtFoDPguJhqp7wYM responded to layer ids request	{"node_id": "d07eb"}
2020-04-20T23:06:46.075+0300	INFO	d07eb.sync         	layer 1452 done	{"node_id": "d07eb"}
2020-04-20T23:06:46.075+0300	INFO	d07eb.sync         	no missing blocks for layer	{"node_id": "d07eb", "layer_id": 1452}
2020-04-20T23:06:46.085+0300	INFO	d07eb.mesh         	Validate layer 1452	{"node_id": "d07eb"}
2020-04-20T23:06:46.085+0300	INFO	d07eb.trtl         	Tortoise update tables	{"node_id": "d07eb", "layer_id": 1452, "n_blocks": 58}
2020-04-20T23:06:52.435+0300	INFO	d07eb.trtl         	found minimal good layer 1451, 1898014584	{"node_id": "d07eb"}
2020-04-20T23:06:52.581+0300	ERROR	d07eb.trtl         	Fatal: goroutine panicked. Stacktrace: goroutine 355 [running]:
runtime/debug.Stack(0xd14340, 0xf31c80, 0xc011472750)
	c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0002550e0, 0xc000170278, 0xc000170268, 0xc000210280, 0x49, 0x0, 0x0, 0x0)
	C:/dev/go-spacemesh/log/zap.go:44 +0x2d
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).addPatternVote.func1(0x6d0a4a3ae4fb04f6, 0xfbc560d4f936b128, 0xc0f5c63ad0)
	C:/dev/go-spacemesh/tortoise/ninja_tortoise.go:444 +0xa17
github.com/spacemeshos/go-spacemesh/tortoise.(*NinjaTortoise).handleIncomingLayer(0xc001bbd320, 0xc0073622e0)
	C:/dev/go-spacemesh/tortoise/ninja_tortoise.go:566 +0x6d7
github.com/spacemeshos/go-spacemesh/tortoise.(*Algorithm).HandleIncomingLayer(0xc006e23d80, 0xc0073622e0, 0x0, 0x0)
	C:/dev/go-spacemesh/tortoise/algorithm.go:56 +0xcf
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).ValidateLayer(0xc0000102c0, 0xc0073622e0)
	C:/dev/go-spacemesh/mesh/mesh.go:212 +0x100
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleNotSynced(0xc000085040, 0x5ac)
	C:/dev/go-spacemesh/sync/syncer.go:344 +0xd1
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc000085040)
	C:/dev/go-spacemesh/sync/syncer.go:301 +0x550
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
	C:/dev/go-spacemesh/sync/syncer.go:258 +0x120
	{"node_id": "d07eb"}
2020-04-20T23:06:52.581+0300	PANIC	d07eb.trtl         	block f604f from layer 1451 has no explicit voting, something went wrong 	{"node_id": "d07eb"}
2020-04-20T23:06:52.582+0300	INFO	d07eb.sync         	close synchronize, Node is out of Sync latest: 1452, maxSynced 9238	{"node_id": "d07eb"}
```

**Comment by lrettig** [comment]
Same issue as #1996
