### ISSUE TITLE
panic: block x from layer x has no explicit voting, something went wrong

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2088]
## Description
My node is dying every time I try to sync the devnet (network id 2). Oddly enough, I resynced from scratch using a different datadir and the sync ran fine.

The same error was reported in a few other issues, looks like it's still an issue:

- #1671
- #1756
- #1999 
- #2010
- #2211
- #2263

## Steps To Reproduce
1. Run go-spacemesh using the devnet config file

## Environment
Please complete the following information:
 - OS: macOS
 - Node Version: `v0.0.0-unreleased+40fbf77ec348a55f24aee1133af1a29b17b67589
`

## Additional Resources 

Partial log below, full log here: https://gist.github.com/lrettig/ecbd9636923fed9f5bb39be557878620

```
2020-07-29T13:06:18.864-0400    INFO    3a2c0.sync              handle layer hash request       {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "layer_id": 234}
2020-07-29T13:06:19.968-0400    INFO    3a2c0.sync              handle layer hash request       {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "layer_id": 235}
2020-07-29T13:06:20.206-0400    INFO    3a2c0.sync              Node is out of sync setting gossip-synced to false and starting sync        {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:20.206-0400    INFO    3a2c0.sync              syncing layer   {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "current_sync_layer": 2189, "last_ticked_layer": 2618}
2020-07-29T13:06:20.206-0400    INFO    3a2c0.sync         .peers               now connected   {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "n_peers": 8}
2020-07-29T13:06:20.206-0400    INFO    3a2c0.sync              fetch layer hash        {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "layer_id": 2189}
2020-07-29T13:06:20.206-0400    INFO    3a2c0.sync         .peers               now connected   {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "n_peers": 8}
2020-07-29T13:06:20.223-0400    WARN    3a2c0.sync              peer Exk6t23hL4SUK67cXbazAJtHvcAbg3ZCn8HKYtPdYS7Q responded with nil to hash request layer 2189     {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:21.380-0400    INFO    3a2c0.sync              layer 2189 has blocks   {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:21.380-0400    INFO    3a2c0.sync              fetch layer ids {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "layer_id": 2189}
2020-07-29T13:06:21.635-0400    INFO    3a2c0.sync              layer 2189 done {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:21.635-0400    INFO    3a2c0.sync              no missing blocks for layer     {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "layer_id": 2189}
2020-07-29T13:06:21.648-0400    INFO    3a2c0.mesh              Validate layer 2189     {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:21.648-0400    INFO    3a2c0.trtl              tortoise update tables  {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92", "layer_id": 2189, "n_blocks": 26}
2020-07-29T13:06:21.907-0400    INFO    3a2c0.trtl              found minimal good layer 2188, 447321181        {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:21.923-0400    ERROR   3a2c0.trtl              Fatal: goroutine panicked. Stacktrace: goroutine 1227 [running]:
runtime/debug.Stack(0x5569500, 0x4b85a60, 0xc00b2ce000)
        /usr/local/Cellar/go/1.14.5/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000417200, 0xc000318378, 0xc000318368, 0xc0000b0320, 0x4e, 0x0, 0x0, 0x0)
        /Users/user/smesh/go-spacemesh2/log/zap.go:46 +0x26
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).addPatternVote.func1(0x15fe4404262d957e, 0xf1c1cfbb4bb94f5f, 0xc01a8e184f)
        /Users/user/smesh/go-spacemesh2/tortoise/ninja_tortoise.go:441 +0xa00
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).handleIncomingLayer(0xc000340480, 0xc008d25f80)
        /Users/user/smesh/go-spacemesh2/tortoise/ninja_tortoise.go:564 +0x5e7
github.com/spacemeshos/go-spacemesh/tortoise.(*tortoise).HandleIncomingLayer(0xc0001bd078, 0xc008d25f80, 0x0, 0x0)
        /Users/user/smesh/go-spacemesh2/tortoise/algorithm.go:69 +0x9f
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc0002e6d30, 0xc008d25f80)
        /Users/user/smesh/go-spacemesh2/mesh/mesh.go:275 +0x10c
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleNotSynced(0xc000251180, 0x88d)
        /Users/user/smesh/go-spacemesh2/sync/syncer.go:423 +0xc8
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc000251180)
        /Users/user/smesh/go-spacemesh2/sync/syncer.go:327 +0x14b
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
        /Users/user/smesh/go-spacemesh2/sync/syncer.go:300 +0x168
        {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
2020-07-29T13:06:21.923-0400    PANIC   3a2c0.trtl              block 7e952d2604 from layer 2187 has no explicit voting, something went wrong       {"node_id": "3a2c0f229af198c034a1298195cd8272045425ca8b7492a48961066c2ede5b92"}
panic: block 7e952d2604 from layer 2187 has no explicit voting, something went wrong

goroutine 1227 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc005d7e0b0, 0x0, 0x0, 0x0)
        /Users/user/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x545
go.uber.org/zap.(*SugaredLogger).log(0xc000318378, 0x504, 0xc0000b0320, 0x4e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/user/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /Users/user/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000417200, 0xc000318378, 0xc000318368, 0xc0000b0320, 0x4e, 0x0, 0x0, 0x0)
        /Users/user/smesh/go-spacemesh2/log/zap.go:47 +0x149
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).addPatternVote.func1(0x15fe4404262d957e, 0xf1c1cfbb4bb94f5f, 0xc01a8e184f)
        /Users/user/smesh/go-spacemesh2/tortoise/ninja_tortoise.go:441 +0xa00
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).handleIncomingLayer(0xc000340480, 0xc008d25f80)
        /Users/user/smesh/go-spacemesh2/tortoise/ninja_tortoise.go:564 +0x5e7
github.com/spacemeshos/go-spacemesh/tortoise.(*tortoise).HandleIncomingLayer(0xc0001bd078, 0xc008d25f80, 0x0, 0x0)
        /Users/user/smesh/go-spacemesh2/tortoise/algorithm.go:69 +0x9f
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc0002e6d30, 0xc008d25f80)
        /Users/user/smesh/go-spacemesh2/mesh/mesh.go:275 +0x10c
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleNotSynced(0xc000251180, 0x88d)
        /Users/user/smesh/go-spacemesh2/sync/syncer.go:423 +0xc8
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc000251180)
        /Users/user/smesh/go-spacemesh2/sync/syncer.go:327 +0x14b
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
        /Users/user/smesh/go-spacemesh2/sync/syncer.go:300 +0x168
```

**Comment by lrettig** [comment]
Someone is [reporting](https://discordapp.com/channels/623195163510046732/691261757921951756/750167583818383430) that this is happening on the new testnet (117). Log attached. Interestingly enough it looks like #1181 may be a factor in this case.

[spacemesh_bug.txt](https://github.com/spacemeshos/go-spacemesh/files/5157847/spacemesh_bug.txt)

**Comment by antonlerner** [comment]
this should be mitigated after the verifying tortoise PR, if not re open
