### ISSUE TITLE
Panic when running in directory without permissions to parent directory: panic: cannot create block builder DB mkdir ../tmp: permission denied

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2148]
## Description
When running go-spacemesh in a directory (cwd) where the current user does not have write permission in the parent directory (e.g., running in one's home directory), the app panics.

## Steps To Reproduce
1. Navigate to a directory where you don't have write permission to the parent directory (i.e., `touch ../foo` fails)
1. Run go-spacemesh (no args needed)

## Environment
Please complete the following information:
 - OS: tested on macOS and Linux, the error occurs on both
 - Node Version: `v0.0.0-unreleased+efb23bf33e19c230c663bc0ea49c0e3edc095829` (efb23bf33e19c230c663bc0ea49c0e3edc095829)

## Additional Resources 
Log:
```
2020-09-23T15:38:55.556Z        INFO    00000.defaultLogger     App version: v0.0.0-unreleased. Git: develop - efb23bf33e
19c230c663bc0ea49c0e3edc095829 . Go Version: go1.15.2. OS: linux-amd64
2020-09-23T15:38:55.556Z        INFO    00000.defaultLogger     initializing event reporter
2020-09-23T15:38:55.556Z        INFO    00000.defaultLogger     Welcome to Spacemesh. Spacemesh full node is starting...
2020-09-23T15:38:55.641Z        INFO    00000.defaultLogger     ntp check from server time-b-wwv.nist.gov, drift: -21.662
877ms, start_check: 2020-09-23 15:38:55.599951593 +0000 UTC, latency: 44.299<C2><B5>s, rsp: 2020-09-23 15:38:55.621592321
 +0000 UTC
...
2020-09-23T15:38:55.784Z        INFO    00000.defaultLogger     System clock synchronized with ntp. drift: -13.630677ms
2020-09-23T15:38:55.784Z        INFO    00000.defaultLogger     Starting Spacemesh      {"data-dir": "data-devnet15b/17",
 "post-dir": "./post-devnet15b"}
2020-09-23T15:38:55.784Z        WARN    00000.defaultLogger     Failed to find identity file: not found
2020-09-23T15:38:55.784Z        WARN    00000.defaultLogger     Created new identity with public key 4a1d59aecf5b7df353d4
f8f18573d345528fd31c97639d84cc6de88bbd048cf5
2020-09-23T15:38:55.797Z        INFO    00000.defaultLogger     Initializing P2P services
2020-09-23T15:38:55.797Z        WARN    4a1d5.p2p               failed to load p2p identity from disk at data-devnet15b/1
7. creating a new identity, err:directory not found data-devnet15b/17  {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd
31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.798Z        INFO    4a1d5.p2p               Local node identity >> 3Ep4C4PxR5dS9DToPNacCqe1jzqpuaeWv7
MGBpyad9NA     {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.798Z        INFO    clock   starting global clock now=2020-09-23 15:38:55.798045255 +0000 UTC m=+0.25
1557259 genesis=2020-09-21 13:29:46.327 +0000 UTC
2020-09-23T15:38:55.798Z        INFO    clock   global clock going to sleep before next layer   {"diff": "50.528655902s",
 "next_layer": 903}
2020-09-23T15:38:55.802Z        INFO    00000.defaultLogger     Saved p2p node information (data-devnet15b/17/p2p/nodes/3
Ep4C4PxR5dS9DToPNacCqe1jzqpuaeWv7MGBpyad9NA/id.json),  Identity - 3Ep4C4PxR5dS9DToPNacCqe1jzqpuaeWv7MGBpyad9NA
2020-09-23T15:38:55.805Z        WARN    4a1d5.p2p               Peers not loaded to addrbook since file does not exist. f
ile=data-devnet15b/17/p2p/peers.json   {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5", "P
2PID": "3Ep4C4PxR5dS9DToPNacCqe1jzqpuaeWv7MGBpyad9NA"}
2020-09-23T15:38:55.805Z        INFO    00000.defaultLogger     not reporting status update as no one is listening
2020-09-23T15:38:55.806Z        INFO    4a1d5.stateDbStore      Allocated cache and file handles        {"node_id": "4a1d
59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5", "cache_size": 16, "num_handles": 16}
...
2020-09-23T15:38:55.926Z        INFO    00000.defaultLogger     started processor with state root 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
2020-09-23T15:38:55.926Z        INFO    4a1d5.meshDb            did not find data to recover on disc    {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.927Z        INFO    4a1d5.trtl              tortoise update tables  {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5", "layer_id": 11, "n_blocks": 1}
2020-09-23T15:38:55.927Z        INFO    4a1d5.app               Genesis account created: 0x1, Balance: %!s(uint64=100000000000000000)   {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.927Z        INFO    4a1d5.app               Genesis account created: 0x7be017a967db77fd10ac7c891b3d6d946dea7e3e14756e2f0f9e09b9663f0d9c, Balance: %!s(uint64=100000000000000000)    {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.927Z        INFO    4a1d5.app               Genesis account created: 0x22a31a84ab876f82fcafba86e77910b4419a4ee0f1d5483d7dd3b5b6b6922ee9, Balance: %!s(uint64=100000000000000000)    {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.928Z        INFO    00000.defaultLogger     not reporting status update as no one is listening
2020-09-23T15:38:55.928Z        INFO    00000.defaultLogger     subscribed to channel
2020-09-23T15:38:55.928Z        INFO    00000.defaultLogger     subscribed to channel
2020-09-23T15:38:55.928Z        INFO    4a1d5.blockBuilder      Allocated cache and file handles        {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5", "cache_size": 16, "num_handles": 16}
2020-09-23T15:38:55.929Z        ERROR   4a1d5.blockBuilder      Fatal: goroutine panicked. Stacktrace: goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.2/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000399b00, 0x104a48b, 0x21, 0xc00052ae90, 0x1, 0x1)
        /home/lane/go-spacemesh/log/zap.go:41 +0xd7
github.com/spacemeshos/go-spacemesh/miner.NewBlockBuilder(0xc0004a30c0, 0x40, 0xc0003fa240, 0xc0, 0xc0, 0xa, 0x64, 0x6, 0x64, 0x7fe64c9edba0, ...)
        /home/lane/go-spacemesh/miner/block_builder.go:103 +0x1ac
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).initServices(0xc000249540, 0xc0004a30c0, 0x40, 0xc0003fa240, 0xc0, 0xc0, 0x118d420, 0xc000388000, 0xc0003fe000, 0x11, ...)
        /home/lane/go-spacemesh/cmd/node/node.go:586 +0x1d12
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc000249540, 0x176dbc0, 0xc0003a6000, 0x0, 0xe)
        /home/lane/go-spacemesh/cmd/node/node.go:1001 +0xe85
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x176dbc0, 0xc0003a6000, 0x0, 0xe)
        /home/lane/go-spacemesh/cmd/node/node.go:102 +0x2f7
github.com/spf13/cobra.(*Command).execute(0x176dbc0, 0xc0000bc010, 0xe, 0xe, 0x176dbc0, 0xc0000bc010)
        /home/lane/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x176dbc0, 0xc000000180, 0xc0001adf78, 0x408905)
        /home/lane/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/lane/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/lane/go-spacemesh/main.go:23 +0xaf
        {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        PANIC   4a1d5.blockBuilder      cannot create block builder DB mkdir ../tmp: permission denied  {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    00000.defaultLogger     App Cleanup starting...
2020-09-23T15:38:55.929Z        INFO    4a1d5.stateDbStore      Database closed {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    4a1d5.atxDbStore        Database closed {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    4a1d5.poetDbStore       Database closed {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    4a1d5.stateDbStore      Database closed {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    4a1d5.store             Database closed {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    4a1d5.appliedTxs        Database closed {"node_id": "4a1d59aecf5b7df353d4f8f18573d345528fd31c97639d84cc6de88bbd048cf5"}
2020-09-23T15:38:55.929Z        INFO    00000.defaultLogger     App Cleanup completed


panic: cannot create block builder DB mkdir ../tmp: permission denied

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002aca50, 0x0, 0x0, 0x0)
        /home/lane/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x55f
go.uber.org/zap.(*SugaredLogger).log(0xc00052ad08, 0x604, 0x104a48b, 0x21, 0xc00052ae90, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/lane/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /home/lane/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000399b00, 0x104a48b, 0x21, 0xc00052ae90, 0x1, 0x1)
        /home/lane/go-spacemesh/log/zap.go:42 +0x277
github.com/spacemeshos/go-spacemesh/miner.NewBlockBuilder(0xc0004a30c0, 0x40, 0xc0003fa240, 0xc0, 0xc0, 0xa, 0x64, 0x6, 0x64, 0x7fe64c9edba0, ...)
        /home/lane/go-spacemesh/miner/block_builder.go:103 +0x1ac
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).initServices(0xc000249540, 0xc0004a30c0, 0x40, 0xc0003fa240, 0xc0, 0xc0, 0x118d420, 0xc000388000, 0xc0003fe000, 0x11, ...)
        /home/lane/go-spacemesh/cmd/node/node.go:586 +0x1d12
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc000249540, 0x176dbc0, 0xc0003a6000, 0x0, 0xe)
        /home/lane/go-spacemesh/cmd/node/node.go:1001 +0xe85
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x176dbc0, 0xc0003a6000, 0x0, 0xe)
        /home/lane/go-spacemesh/cmd/node/node.go:102 +0x2f7
github.com/spf13/cobra.(*Command).execute(0x176dbc0, 0xc0000bc010, 0xe, 0xe, 0x176dbc0, 0xc0000bc010)
        /home/lane/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x176dbc0, 0xc000000180, 0xc0001adf78, 0x408905)
        /home/lane/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/lane/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/lane/go-spacemesh/main.go:23 +0xaf
```

**Comment by lrettig** [comment]
I cleaned up one of these in 5511b0bc3c184406ebb61e305a3d94bd6a3b2225, I still see a few:

```
go-spacemesh> ag "tmp"
mesh/meshdb_test.go
25:     Path = "../tmp/mdb"

cmd/node/multi_node_test.go
9:      StartMultiNode(5, 10, 10, "/tmp/data")

database/interface.go
88:     Path:    "../tmp/test/" + time.Now().String(),

activation/activation_test.go
706:    drive := "/tmp/anton"

activation/nipst_test.go
148:    datadir := "/tmp/anton"

activation/activationdb_test.go
766:    const tmpPath = "../tmp/atx"

api/grpcserver/grpcserver_test.go
48:     dataDir               = "/tmp"

sync/syncer_test.go
60:     Path     = "../tmp/sync/"

tortoise/ninja_tortoise_test.go
17:const Path = "../tmp/tortoise/"
```

These should all be rewritten to use [`ioctl.TempDir`](https://golang.org/pkg/io/ioutil/#TempDir)

**Comment by lrettig** [comment]
I'm getting this error on Windows now too:

```
2020-10-01T15:13:17.782-0400    INFO    49bb5.blockBuilder      Allocated cache and file handles        {"node_id": "49bb528b9441d117eda29bce8fe26254706e89be12c34e4378c6f4d0a61505bf", "cache_size": 16, "num_handles": 16}
2020-10-01T15:13:17.782-0400    ERROR   49bb5.blockBuilder      Fatal: goroutine panicked. Stacktrace: goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc00021ccc0, 0x1147860, 0x21, 0xc0004b6e80, 0x1, 0x1)
        C:/Users/lanerettig/wip/go-spacemesh/log/zap.go:41 +0xc5
github.com/spacemeshos/go-spacemesh/miner.NewBlockBuilder(0xc00037f8c0, 0x40, 0xc00010c300, 0xc0, 0xc0, 0xa, 0x19, 0x120, 0x64, 0x32ac158, ...)
        C:/Users/lanerettig/wip/go-spacemesh/miner/block_builder.go:103 +0x1b7
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).initServices(0xc000297400, 0xc00037f8c0, 0x40, 0xc00010c300, 0xc0, 0xc0, 0x12e96e0, 0xc0000cf400, 0xc00037f9c0, 0x3b, ...)
        C:/Users/lanerettig/wip/go-spacemesh/cmd/node/node.go:587 +0x1cf3
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc000297400, 0xea90c0, 0xc0000d8d00, 0x0, 0x8)
        C:/Users/lanerettig/wip/go-spacemesh/cmd/node/node.go:1002 +0xe5b
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0xea90c0, 0xc0000d8d00, 0x0, 0x8)
        C:/Users/lanerettig/wip/go-spacemesh/cmd/node/node.go:103 +0x2fa
github.com/spf13/cobra.(*Command).execute(0xea90c0, 0xc0000da010, 0x8, 0xf, 0xea90c0, 0xc0000da010)
        C:/Users/lanerettig/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0xea90c0, 0xc000044000, 0xc0001b5f78, 0x4064d6)
        C:/Users/lanerettig/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/lanerettig/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        C:/Users/lanerettig/wip/go-spacemesh/main.go:23 +0xb3
        {"node_id": "49bb528b9441d117eda29bce8fe26254706e89be12c34e4378c6f4d0a61505bf"}
2020-10-01T15:13:17.782-0400    PANIC   49bb5.blockBuilder      cannot create block builder DB CreateFile ../tmp/test/2020-10-01 15:13:16.8655566 -0400 -04 m=+0.015687001builder: The filename, directory name, or volume label syntax is incorrect.   {"node_id": "49bb528b9441d117eda29bce8fe26254706e89be12c34e4378c6f4d0a61505bf"}
2020-10-01T15:13:17.783-0400    INFO    00000.defaultLogger     App Cleanup starting...
```

**Comment by lrettig** [comment]
Looks like this issue was introduced in #2011, something to do with the way the database is set up in the blockBuilder. CC @antonlerner 

BTW my comment above (https://github.com/spacemeshos/go-spacemesh/issues/2148#issuecomment-700256243) was referring to tests, but this issue is not about tests, it's about the production code. The tests should be cleaned up as well but that's much lower priority.
