### ISSUE TITLE
PANIC	TestNinjaTortoise_Recovery	error block not found

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2195]
## Description
I've seen this panic occur in the unittests several times recently, sporadically:

2020-11-06T22:56:59.214Z	ERROR	TestNinjaTortoise_Recovery	Fatal: goroutine panicked. Stacktrace: goroutine 387 [running]:
runtime/debug.Stack(0x4e2502, 0xc0001460c8, 0xaa3cb0)
	/opt/hostedtoolcache/go/1.14.6/x64/src/runtime/debug/stack.go:24 +0x9d
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc00006c420, 0xc0001c2180, 0x3d, 0x0, 0x0, 0x0)
	/home/runner/work/go-spacemesh/go-spacemesh/log/zap.go:41 +0xbe
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).processBlock(0xc0000ba580, 0xc0001b8100)
	/home/runner/work/go-spacemesh/go-spacemesh/tortoise/ninja_tortoise.go:222 +0x498
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).processBlocks(0xc0000ba580, 0xc010b1cae0)
	/home/runner/work/go-spacemesh/go-spacemesh/tortoise/ninja_tortoise.go:483 +0x53
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).handleIncomingLayer(0xc0000ba580, 0xc010b1cae0)
	/home/runner/work/go-spacemesh/go-spacemesh/tortoise/ninja_tortoise.go:528 +0x27b
github.com/spacemeshos/go-spacemesh/tortoise.(*tortoise).HandleIncomingLayer(0xc0000a2300, 0xc010b1cae0, 0x0, 0x0)
	/home/runner/work/go-spacemesh/go-spacemesh/tortoise/algorithm.go:69 +0x9f
github.com/spacemeshos/go-spacemesh/tortoise.TestNinjaTortoise_Recovery(0xc0000ce480)
	/home/runner/work/go-spacemesh/go-spacemesh/tortoise/ninja_tortoise_test.go:1043 +0x357
testing.tRunner(0xc0000ce480, 0xab6330)
	/opt/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1090 +0x372

2020-11-06T22:56:59.214Z	PANIC	TestNinjaTortoise_Recovery	error block not found ID d853ac02ad , leveldb: not found!!!!!
    ninja_tortoise_test.go:1023: Recovered from error block not found ID d853ac02ad , leveldb: not found!!!!!

Full log: https://github.com/spacemeshos/go-spacemesh/runs/1366070483?check_suite_focus=true

## Steps To Reproduce
1. Run `TestNinjaTortoise_Recovery` test

## Environment
Please complete the following information:
 - OS: GitHub Actions CI, ubuntu-latest
 - Node Version: 876dca712b53e1ec8fe4e23180f8dd6e9940e371

**Comment by lrettig** [comment]
Okay I think this is expected :)
