### ISSUE TITLE
block * from layer * has no explicit voting, something went wrong

### ISSUE THREAD

**Issue by sl-he** [spacemeshos/go-spacemesh#2263]
## Description
Node is crashed with this error log
```
2021-01-18T15:18:27.460Z        ERROR   8101d.trtl              Fatal: goroutine panicked. Stacktrace: goroutine 2734 [running]:
runtime/debug.Stack(0x4fba72, 0xc00edb0a1f, 0x114ca3f)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000dc7380, 0xc000040320, 0x4d, 0x0, 0x0, 0x0)
        /root/source/go-spacemesh/log/zap.go:42 +0xd7
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).addPatternVote.func1(0x47c1caaf98ef23d0, 0xbe18462bcf2ebc66, 0xc070583d39)
        /root/source/go-spacemesh/tortoise/ninja_tortoise.go:440 +0xb66
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).handleIncomingLayer(0xc00002c2c0, 0xc00e3fed40)
        /root/source/go-spacemesh/tortoise/ninja_tortoise.go:567 +0x5ff
github.com/spacemeshos/go-spacemesh/tortoise.(*tortoise).HandleIncomingLayer(0xc00911d320, 0xc00e3fed40, 0x0, 0x0)
        /root/source/go-spacemesh/tortoise/algorithm.go:69 +0xa6
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc00006b600, 0xc00e3fed40)
        /root/source/go-spacemesh/mesh/mesh.go:280 +0xcb
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getAndValidateLayer(0xc00033cb40, 0x392, 0x0, 0x0)
        /root/source/go-spacemesh/sync/syncer.go:1248 +0xe4
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleCurrentLayer(0xc00033cb40, 0x111fa00, 0x15)
        /root/source/go-spacemesh/sync/syncer.go:415 +0x1dc
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleWeaklySynced(0xc00033cb40)
        /root/source/go-spacemesh/sync/syncer.go:372 +0x157
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc00033cb40)
        /root/source/go-spacemesh/sync/syncer.go:348 +0x11a
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
        /root/source/go-spacemesh/sync/syncer.go:323 +0x155
        {"node_id": "8101d63f2f835c83389b15d846bd362270434433bb9d67ea78eaaf63da3c0235"}
2021-01-18T15:18:27.473Z        PANIC   8101d.trtl              block d023ef98af from layer 913 has no explicit voting, something went wrong    {"node_id": "8101d63f2f835c83389b15d846bd362270434433bb9d67ea78eaaf63da3c0235"}
panic: block d023ef98af from layer 913 has no explicit voting, something went wrong

goroutine 2734 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000292160, 0x0, 0x0, 0x0)
        /root/work/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x55f
go.uber.org/zap.(*SugaredLogger).log(0xc0085e5188, 0x604, 0xc000040320, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/work/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /root/work/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000dc7380, 0xc000040320, 0x4d, 0x0, 0x0, 0x0)
        /root/source/go-spacemesh/log/zap.go:43 +0x277
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).addPatternVote.func1(0x47c1caaf98ef23d0, 0xbe18462bcf2ebc66, 0xc070583d39)
        /root/source/go-spacemesh/tortoise/ninja_tortoise.go:440 +0xb66
github.com/spacemeshos/go-spacemesh/tortoise.(*ninjaTortoise).handleIncomingLayer(0xc00002c2c0, 0xc00e3fed40)
        /root/source/go-spacemesh/tortoise/ninja_tortoise.go:567 +0x5ff
github.com/spacemeshos/go-spacemesh/tortoise.(*tortoise).HandleIncomingLayer(0xc00911d320, 0xc00e3fed40, 0x0, 0x0)
        /root/source/go-spacemesh/tortoise/algorithm.go:69 +0xa6
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc00006b600, 0xc00e3fed40)
        /root/source/go-spacemesh/mesh/mesh.go:280 +0xcb
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getAndValidateLayer(0xc00033cb40, 0x392, 0x0, 0x0)
        /root/source/go-spacemesh/sync/syncer.go:1248 +0xe4
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleCurrentLayer(0xc00033cb40, 0x111fa00, 0x15)
        /root/source/go-spacemesh/sync/syncer.go:415 +0x1dc
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleWeaklySynced(0xc00033cb40)
        /root/source/go-spacemesh/sync/syncer.go:372 +0x157
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc00033cb40)
        /root/source/go-spacemesh/sync/syncer.go:348 +0x11a
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run
        /root/source/go-spacemesh/sync/syncer.go:323 +0x155
```

## Steps To Reproduce
1. Just run node and wait a few dozens of minutes
2. See error

## Expected Behavior
Running node without any errors ;)

## Environment
Please complete the following information:
 - OS: Ubuntu 18.04.5 LTS
 - Node Version: v0.1.22+1b3e38ace6840e1384bee4ce86b393cafabca966

**Comment by noamnelke** [comment]
As discussed on Discord (putting it here for the record):

This is a known issue that we don't have enough data on to investigate and resolve. If it happens again, we'd appreciate getting the full logs from the node.

I'm closing this issue for now - feel free to re-open it or open a new one if it happens again and you have the full logs.

**Comment by sl-he** [comment]
All logs for spasemesh node app from start to unenspected closing
https://pastebin.com/uABgAVFY

**Comment by noamnelke** [comment]
Thanks @sl-he!

@antonlerner @y0sher can you take a look?

**Comment by lrettig** [comment]
This is happening because a block is voting for another block that tortoise has not seen, i.e., the voted-for block never passed through `processBlock()`. It's listed in the view, because it's been voted for, but it has no explicit vote recorded. I'm not sure why this happens.
