### ISSUE TITLE
Hare panic: Tried to update a previous layer

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2291]
## Description

A testnet user (Tweedledee 124) reported the following panic:

2021-02-17T18:48:59.984+0100    ERROR   75077.hare              Fatal: goroutine panicked. Stacktrace: goroutine 136 [running]:\
runtime/debug.Stack(0x1, 0x27e2858, 0x203006)\
        /Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/debug/stack.go:24 +0x9d\
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0004647e0, 0x1d1f058, 0x31, 0xc005a07b00, 0x2, 0x2)\
        /Users/runner/work/go-spacemesh/go-spacemesh/log/zap.go:42 +0xbe\
github.com/spacemeshos/go-spacemesh/hare.(*Broker).updateLatestLayer(...)\
        /Users/runner/work/go-spacemesh/go-spacemesh/hare/broker.go:239\
github.com/spacemeshos/go-spacemesh/hare.(*Broker).Register.func1()\
        /Users/runner/work/go-spacemesh/go-spacemesh/hare/broker.go:290 +0x394\
github.com/spacemeshos/go-spacemesh/hare.(*Broker).eventLoop(0xc000096640)\
        /Users/runner/work/go-spacemesh/go-spacemesh/hare/broker.go:229 +0x1297\
created by github.com/spacemeshos/go-spacemesh/hare.(*Broker).Start\
        /Users/runner/work/go-spacemesh/go-spacemesh/hare/broker.go:93 +0x9e\
        \{"node_id": "75077565847866ef80fe08b37d80fee23425ade84802204ff2177c2197a722de"\}\
2021-02-17T18:48:59.984+0100    PANIC   75077.hare              Tried to update a previous layer expected 2981 > 2982   \{"node_id": "75077565847866ef80fe08b37d80fee23425ade84802204ff2177c2197a722de"\}}

## Steps To Reproduce
Unclear

## Expected Behavior
Unclear (but not a panic)

## Environment
 - OS: macOS
 - Node Version: 0.1.23
 - App Version (if applicable): ?

## Additional Resources 
Logs (partial): https://discordapp.com/channels/623195163510046732/691261757921951756/811692484723867679

I'm working on getting more information and complete logs.

**Comment by lrettig** [comment]
This node is missing most layer ticks, which could be related:

```
> egrep 'ticker|clock' log.txt
2021-02-17T18:12:44.032+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:12:44.032+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:12:44.032+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "14.042ms", "next_layer": 2975\}\
2021-02-17T18:12:44.047+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2976\}\
2021-02-17T18:12:44.047+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.999363s", "next_layer": 2976\}\
2021-02-17T18:17:44.032+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:17:44.032+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:17:44.032+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "14.027ms", "next_layer": 2976\}\
2021-02-17T18:17:44.048+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2977\}\
2021-02-17T18:17:44.048+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.998329s", "next_layer": 2977\}\
2021-02-17T18:22:44.031+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:22:44.031+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:22:44.031+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "15.136ms", "next_layer": 2977\}\
2021-02-17T18:22:44.047+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2978\}\
2021-02-17T18:22:44.047+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.999265s", "next_layer": 2978\}\
2021-02-17T18:27:44.033+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:27:44.033+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:27:44.033+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "13.226ms", "next_layer": 2978\}\
2021-02-17T18:27:44.048+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2979\}\
2021-02-17T18:27:44.049+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.998002s", "next_layer": 2979\}\
2021-02-17T18:32:44.032+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:32:44.032+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:32:44.032+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "14.684ms", "next_layer": 2979\}\
2021-02-17T18:32:44.048+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2980\}\
2021-02-17T18:32:44.048+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.998515s", "next_layer": 2980\}\
2021-02-17T18:37:44.053+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2981\}\
2021-02-17T18:37:44.053+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.993185s", "next_layer": 2981\}\
2021-02-17T18:42:44.038+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:42:44.038+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:42:44.038+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "8.254ms", "next_layer": 2981\}\
2021-02-17T18:42:44.047+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2982\}\
2021-02-17T18:42:44.047+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.999696s", "next_layer": 2982\}\
2021-02-17T18:47:44.033+0100    WARN    ticker  skipping tick since we missed the time of the tick by more than the allowed threshold   \{"threshold": "500ms"\}\
2021-02-17T18:47:44.033+0100    ERROR   clock   could not notify subscribers    \{"errmsg": "missed tick time by more than the allowed threshold", "missed": 0\}\
2021-02-17T18:47:44.033+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "13.842ms", "next_layer": 2982\}\
2021-02-17T18:47:44.049+0100    INFO    ticker  release tick    \{"event": true, "layer_id": 2983\}\
2021-02-17T18:47:44.049+0100    INFO    clock   global clock going to sleep before next layer   \{"diff": "4m59.997729s", "next_layer": 2983\}\
```

It's impossible to debug this further without debug logs for hare. It could be a bug in the hare broker. I noticed that the broker does not wrap `latestLayer` in a mutex. Somehow, it's trying to register layer 2981 eleven minutes after the layer tick for this layer, when the `hare-wakeup-delta` is set to 30s. This doesn't make sense.
