### ISSUE TITLE
Out of memory managed miner panic

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2313]
## Description
A managed miner on testnet126 crashed with an out of memory panic.

## Steps To Reproduce
Unclear

## Expected Behavior
Unclear

## Environment
Please complete the following information:
 - OS: Linux (docker)
 - Node Version: v0.1.26
 - App Version (if applicable): N/A

## Additional Resources 
Partial logs: https://drive.google.com/file/d/1k6Y2PNa2s0QqbsYQ-MbgHuGrYQOjqMdM/view?usp=sharing

Here's part of the log:

```
{"L":"INFO","T":"2021-03-05T07:12:15.475Z","N":"52afd.sync         ","M":"epoch 2 has atxs","node_id":"52afdc51e732564a04e38a3a05d96692cc5040ec9e4c5826d5a7ae7105b9468a"}
{"L":"INFO","T":"2021-03-05T07:12:15.477Z","N":"52afd.sync         ","M":"fetched 81 atxs for epoch 2 actual map [[0 22 166 248 80 120 250 223 158 112 145 116 44 204 70 195 50
152 207 86 215 129 38 182 159 101 72 24 31 ...93]]","node_id":"52afdc51e732564a04e38a3a05d96692cc5040ec9e4c5826d5a7ae7105b9468a"}
{"L":"INFO","T":"2021-03-05T07:12:15.684Z","N":"52afd.sync         ","M":"sync state w: true, g:2 layer : 641 latest: 641","node_id":"52afdc51e732564a04e38a3a05d96692cc5040ec9e4c5826d5a7ae7105b9468a"}
{"L":"INFO","T":"2021-03-05T07:12:16.688Z","N":"52afd.sync         ","M":"sync state w: true, g:2 layer : 641 latest: 641","node_id":"52afdc51e732564a04e38a3a05d96692cc5040ec9e4c5826d5a7ae7105b9468a"}
{"L":"INFO","T":"2021-03-05T07:12:17.691Z","N":"52afd.sync         ","M":"sync state w: true, g:2 layer : 641 latest: 641","node_id":"52afdc51e732564a04e38a3a05d96692cc5040ec9e4c5826d5a7ae7105b9468a"}
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1103b34, 0x16)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc038000000, 0x3ee10000000, 0x1be6e98)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1bd1e00, 0x3ee0d800000, 0x1bd1e08, 0x1f706b23)
        /usr/local/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x1bd1e00, 0x1f706b23, 0x0)
        /usr/local/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x1bd1e00, 0x1f706b23, 0x7fdb00000100, 0x1be6ea8, 0x2)
        /usr/local/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x1bd1e00, 0x1f706b23, 0x460101, 0x1bd1e00)
        /usr/local/go/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x3ee0d645a18, 0xc000720101, 0x4)
        /usr/local/go/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x25)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1041

goroutine 1734300 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc000078e18 sp=0xc000078e10 pc=0x467360
runtime.mallocgc(0x3ee0d645a18, 0xf07460, 0x1, 0x5)
        /usr/local/go/src/runtime/malloc.go:1046 +0x895 fp=0xc000078eb8 sp=0xc000078e18 pc=0x40e995
runtime.makeslice(0xf07460, 0x3ee0d645a18, 0x3ee0d645a18, 0x0)
        /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc000078ee8 sp=0xc000078eb8 pc=0x44e3ec
github.com/spacemeshos/go-spacemesh/p2p/net/wire/delimited.(*Reader).Next(0xc01759e160, 0x12e0940, 0xc000444460, 0xc006d26660, 0x12, 0x12)
        /go/src/github.com/spacemeshos/go-spacemesh/p2p/net/wire/delimited/delimited.go:66 +0x136 fp=0xc000078f48 sp=0xc000078ee8 pc=0xdcd596
github.com/spacemeshos/go-spacemesh/p2p/net.(*FormattedConnection).beginEventProcessing(0xc000444460)
        /go/src/github.com/spacemeshos/go-spacemesh/p2p/net/conn.go:364 +0x4c fp=0xc000078fd8 sp=0xc000078f48 pc=0xdcff2c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000078fe0 sp=0xc000078fd8 pc=0x469471
created by github.com/spacemeshos/go-spacemesh/p2p/net.(*Net).accept.func1
        /go/src/github.com/spacemeshos/go-spacemesh/p2p/net/network.go:314 +0x3d4

goroutine 1 [chan receive, 3200 minutes]:
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).Start(0xc000272c80, 0x1b93740, 0xc00032ea20, 0x0, 0x11)
        /go/src/github.com/spacemeshos/go-spacemesh/cmd/node/node.go:1066 +0x100f
github.com/spacemeshos/go-spacemesh/cmd/node.glob..func1(0x1b93740, 0xc00032ea20, 0x0, 0x11)
        /go/src/github.com/spacemeshos/go-spacemesh/cmd/node/node.go:102 +0x2f3
github.com/spf13/cobra.(*Command).execute(0x1b93740, 0xc000138010, 0x11, 0x11, 0x1b93740, 0xc000138010)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1b93740, 0xc000000180, 0xc0004dff78, 0x4078df)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /go/src/github.com/spacemeshos/go-spacemesh/main.go:23 +0xac

goroutine 5 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00004e980)
        /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x100
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68

...
```

**Comment by web3rover** [comment]
@lrettig Here is the docker logs output of miner58 https://storage.googleapis.com/spacecraft-data/tweedlelite126-archive/miner58-docker-output-logs.zip

**Comment by lrettig** [comment]
Here's strong evidence of a memory leak:

```
> grep -A 1 goroutine stdout-56.log | grep github.com | sort -k 1,6 | uniq -w 60 -c | sort -nr
    872 github.com/spacemeshos/go-spacemesh/p2p/net.(*udpConnWrapper).Read(0xc00004ee00, 0xc000bda000, 0x7530, 0x7530, 0xcc, 0xcc, 0x0)
    287 github.com/spacemeshos/go-spacemesh/p2p/net.(*FormattedConnection).sendListener(0xc000012000)
    206 github.com/spacemeshos/go-spacemesh/p2p/net.(*MsgConnection).sendListener(0xc0000bdad0)
     48 github.com/spacemeshos/go-spacemesh/sync.newFetchWorker.func1()
     48 github.com/spacemeshos/go-spacemesh/sync.(*fetchQueue).work.func1(0xc00021e900, 0xc0008660c0, 0xc000518080)
     13 github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000012460)
     13 github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc000192690)
     13 github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0002401a0)
     13 github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0002401a0)
     13 github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0002401a0)
     13 github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0002401a0)
      6 github.com/spacemeshos/go-spacemesh/p2p.(*Switch).listenToNetworkMessages.func1(0xc0001d0500, 0xc0003386c0)
      4 github.com/spacemeshos/go-spacemesh/p2p/peers.(*Peers).listenToPeers(0xc0005a6500, 0xc000338b40, 0xc000338ba0)
      3 github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).checkTimeDrifts(0xc000276dc0)
      2 github.com/spacemeshos/go-spacemesh/p2p/service.(*Listener).listenToGossip(0xc000122540, 0xc00048a5b0, 0xc0006acc60, 0xc0005933e0)
      2 github.com/spacemeshos/go-spacemesh/p2p/server.(*MessageServer).readLoop(0xc000392360)
      1 github.com/spacemeshos/go-spacemesh/timesync.(*TimeClock).startClock(0xc000126050)
      1 github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run(0xc000819400)
      1 github.com/spacemeshos/go-spacemesh/sync.(*BlockListener).listenToGossipBlocks(0xc0006ac8a0)
      1 github.com/spacemeshos/go-spacemesh/priorityq.(*Queue).Read(0xc0005b4040, 0xc019ea0000, 0x8130, 0x8130, 0x4dad042676ce4046)
      1 github.com/spacemeshos/go-spacemesh/p2p.(*UDPMux).listenToNetworkMessage(0xc00018a070)
      1 github.com/spacemeshos/go-spacemesh/p2p.(*Switch).peersLoop(0xc0001d0500)
      1 github.com/spacemeshos/go-spacemesh/p2p/gossip.(*Protocol).propagationEventLoop(0xc00027f1e0)
      1 github.com/spacemeshos/go-spacemesh/p2p/discovery.(*addrBook).saveRoutine(0xc000198500, 0xc0003cc3c0, 0x22)
      1 github.com/spacemeshos/go-spacemesh/miner.(*BlockBuilder).createBlockLoop(0xc0007ca500)
      1 github.com/spacemeshos/go-spacemesh/hare.(*Hare).tickLoop(0xc0007ca140)
      1 github.com/spacemeshos/go-spacemesh/hare.(*Hare).outputCollectionLoop(0xc0007ca140)
      1 github.com/spacemeshos/go-spacemesh/hare.(*consensusProcess).eventLoop(0xc00a444000)
      1 github.com/spacemeshos/go-spacemesh/hare.(*Broker).eventLoop(0xc000850000)
      1 github.com/spacemeshos/go-spacemesh/events.SubscribeToLayers.func1(0xc0004b6240)
      1 github.com/spacemeshos/go-spacemesh/api/pb.RegisterSpacemeshServiceHandlerFromEndpoint.func1.1(0x12cff40, 0xc000042050, 0xc000640380, 0xc00027c030, 0xf)
      1 github.com/spacemeshos/go-spacemesh/activation.(*PoetListener).loop(0xc0006c6380)
      1 github.com/spacemeshos/go-spacemesh/activation.(*Builder).waitOrStop(0xc0007ca640, 0xc000a51020, 0xc000a51020, 0xc004b3bc08)
```

Logs are [here](https://drive.google.com/file/d/1y3I9UC1PBaUAWg_ToKVYOQzEbmi1kbFf/view?usp=sharing)
