### ISSUE TITLE
panic: could not find transactions

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2460]
## Description
Several testnet nodes have died with this error/panic:

```
could not find transactions map[0x28cc1ef7cec29714bb259cb9efdc7e62862fc822e55181ab23de3ce0436aa216:{} 0x4be02998c081eee8696324bcfe4c360225604d2fd9bb473b1a6164470a9e8b41:{}] from layer 1240

Fatal: goroutine panicked. Stacktrace: goroutine 3733776 [running]: runtime/debug.Stack(0xc016355b20, 0x106c72a, 0x6) /usr/local/go/src/runtime/debug/stack.go:24 +0x9d github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000400300, 0x106ab58, 0x4, 0x1099446, 0x2c, 0xc001dc6750, 0x2, 0x2) /go/src/github.com/spacemeshos/go-spacemesh/log/zap.go:45 +0xbe github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).getTxs(0xc0001be580, 0xc0096c6800, 0x2a, 0x40, 0x4d8, 0x2a, 0x40, 0xd5bd039639fb0b88) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:549 +0x16d github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).extractUniqueOrderedTransactions(0xc0001be580, 0xc0267f4840, 0xc02d5aa6c0, 0x40, 0xc016cec978) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:520 +0x38f github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).accumulateRewards(0xc0001be580, 0xc0267f4840, 0xc0004d0d60) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:786 +0x925 github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).applyState(0xc0001be580, 0xc0267f4840) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:355 +0xb4 github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).updateStateWithLayer(0xc0001be580, 0x4d7, 0xc0145f87e0) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:431 +0x109 github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).pushLayersToState(0xc0001be580, 0x4d7, 0x4d8) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:312 +0x5a github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc0000ae200, 0xc017a80d00) /go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:291 +0x1cc github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getAndValidateLayer(0xc0001be6e0, 0x4d9, 0x0, 0x0) /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:1330 +0xea github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleCurrentLayer(0xc0001be6e0, 0x1247fe0, 0xc009b00030, 0x107c653, 0x15) /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:443 +0x1ed github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleWeaklySynced(0xc0001be6e0, 0x1247fe0, 0xc009b00030) /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:390 +0x213 github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc0001be6e0, 0x1247fe0, 0xc009b00030) /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:362 +0x1bb created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run /go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:334 +0x278

/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0x100
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:291 +0x1cc
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).getAndValidateLayer(0xc0001be6e0, 0x4d9, 0x0, 0x0)
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleCurrentLayer(0xc0001be6e0, 0x1247fe0, 0xc009b00030, 0x107c653, 0x15)
/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:362 +0x1bb
panic: could not find transactions map[0x28cc1ef7cec29714bb259cb9efdc7e62862fc822e55181ab23de3ce0436aa216:{} 0x4be02998c081eee8696324bcfe4c360225604d2fd9bb473b1a6164470a9e8b41:{}] from layer 1240
goroutine 3733776 [running]:
go.uber.org/zap.(*SugaredLogger).log(0xc001dc6600, 0x904, 0x1099446, 0x2c, 0xc001dc6750, 0x2, 0x2, 0x0, 0x0, 0x0)
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:520 +0x38f
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).pushLayersToState(0xc0001be580, 0x4d7, 0x4d8)
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:431 +0x109
/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x545
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000400300, 0x106ab58, 0x4, 0x1099446, 0x2c, 0xc001dc6750, 0x2, 0x2)
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).getTxs(0xc0001be580, 0xc0096c6800, 0x2a, 0x40, 0x4d8, 0x2a, 0x40, 0xd5bd039639fb0b88)
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).extractUniqueOrderedTransactions(0xc0001be580, 0xc0267f4840, 0xc02d5aa6c0, 0x40, 0xc016cec978)
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).accumulateRewards(0xc0001be580, 0xc0267f4840, 0xc0004d0d60)
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:786 +0x925
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).updateStateWithLayer(0xc0001be580, 0x4d7, 0xc0145f87e0)
/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:390 +0x213
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).synchronise(0xc0001be6e0, 0x1247fe0, 0xc009b00030)
created by github.com/spacemeshos/go-spacemesh/sync.(*Syncer).run

go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00001a000, 0x0, 0x0, 0x0)
go.uber.org/zap.(*SugaredLogger).Panicf(...)
/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
/go/src/github.com/spacemeshos/go-spacemesh/log/zap.go:46 +0x25f
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:549 +0x16d
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).applyState(0xc0001be580, 0xc0267f4840)
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:355 +0xb4
/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:312 +0x5a
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc0000ae200, 0xc017a80d00)
/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:1330 +0xea
/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:443 +0x1ed
github.com/spacemeshos/go-spacemesh/sync.(*Syncer).handleWeaklySynced(0xc0001be6e0, 0x1247fe0, 0xc009b00030)
/go/src/github.com/spacemeshos/go-spacemesh/sync/syncer.go:334 +0x278
```

## Expected Behavior
unclear

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: v0.1.38

**Comment by lrettig** [comment]
Here's a full debug trace of one of these txids:

```
2021-06-15T14:47:17.499-0400	ERROR	99a8a.state        	nonce and balance validation failed	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "requestId": "3630a9a9-e853-4822-b84e-ea6629e4ec0a", "channel": "TxGossip", "sessionId": "2a6463ae-563e-41f2-8188-1913e1b7db16", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect account nonce! Expected: 920, Actual: 1076", "name": "state"}
2021-06-15T14:51:26.985-0400	DEBUG	99a8a.sync         .txFetchQueue 	going to fetch txs	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "layer_id": 1242, "requestId": "cf218953-fa28-4404-8f71-6a12d7485534", "channel": "newBlock", "sessionId": "4f362abb-5b35-4c86-ae4f-a01dbbacfe50", ...
"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "tx_id": ... "name": "sync.txFetchQueue"}
2021-06-15T14:51:26.985-0400	DEBUG	99a8a.sync         	tx not in tx pool	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "layer_id": 1242, "requestId": "cf218953-fa28-4404-8f71-6a12d7485534", "channel": "newBlock", "sessionId": "4f362abb-5b35-4c86-ae4f-a01dbbacfe50", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "name": "sync"}
2021-06-15T14:51:26.986-0400	WARN	99a8a.meshDb       	could not fetch tx	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "meshDb", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "could not find transaction in database 07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e err=leveldb: not found", "name": "meshDb"}
2021-06-15T14:51:26.992-0400	INFO	99a8a.sync         .FetchWrker   	send fetch request	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "peer_id": "9DqW1tt3FeqnFmeboLh4twLNTm6ax53sqSBNNQn8asnY", "type": "Tx", "ids": "c09078e6a0 c4bfaf8343 9b0ac06b45 d9ea2e855f 15c1110300 c58d0f9efb 5bc31372c2 00b63c8e46 4011e579ff 6a1db5f4c7 9e3b738f26 be9107a50b ec9b64fa4c 4b764c1b1b 398d5eb619 7da34c14c0 1bef16b3f2 d991305e3f 169f3df4ec 520e01ae1a d6bfc7fcdb 11269d5a72 bb87ab2796 db81af0191 d60e55fc8a f3ffd9e29e cbc9dbebc2 1ad3da43f7 2c6ce6556b fac5ab2617 e11287d570 8eecbcbfce 15bd3ee022 979b3bce73 a661973699 892ae0d8ef 3d229cd74d 63760769bf 25a4455fae 6700621f84 fc199dc2c1 229cd97cda c479e8d719 d72dcf13e9 a04496cbae ba1c81b46a a7ba798b29 d02a0695f6 7552cc4ef8 4933b686fd ad495d5077 07c1c7f786 41d021a83b 6344b173c0 79f927fc8b d0f152f0ab f1e3a62f48 518aed2a86 714240d584 c6bb2a2a5a f9d02cb438 08f2bc035b 3f75cdc744 5b3fcc2f7b 14719c0f85 f5a9c6df99 5a35c36772 2787b13183 3c2ca92b9b 38d444f3f8 ebec88c56f 28fb3976b5 beb8944a2e", "name": "sync.FetchWrker"}
2021-06-15T14:51:28.380-0400	WARN	99a8a.sync         	item was not in response	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "hash": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "name": "sync"}
2021-06-15T14:51:28.380-0400	INFO	99a8a.sync         .FetchWrker   	send fetch request	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "peer_id": "9mzBmDoNH7TYJG8afBwK71ofa4VhQ9TrFj15NvBVYPeu", "type": "Tx", "ids": "d991305e3f 169f3df4ec 520e01ae1a d6bfc7fcdb 11269d5a72 bb87ab2796 1bef16b3f2 d60e55fc8a f3ffd9e29e cbc9dbebc2 1ad3da43f7 2c6ce6556b fac5ab2617 e11287d570 db81af0191 15bd3ee022 979b3bce73 a661973699 892ae0d8ef 8eecbcbfce 63760769bf 25a4455fae 6700621f84 fc199dc2c1 3d229cd74d c479e8d719 d72dcf13e9 229cd97cda ba1c81b46a a7ba798b29 a04496cbae 7552cc4ef8 4933b686fd ad495d5077 07c1c7f786 d02a0695f6 6344b173c0 79f927fc8b d0f152f0ab f1e3a62f48 518aed2a86 41d021a83b c6bb2a2a5a f9d02cb438 714240d584 3f75cdc744 5b3fcc2f7b 14719c0f85 08f2bc035b 5a35c36772 f5a9c6df99 3c2ca92b9b 38d444f3f8 ebec88c56f 2787b13183 beb8944a2e 28fb3976b5 c4bfaf8343 9b0ac06b45 d9ea2e855f 15c1110300 c58d0f9efb c09078e6a0 00b63c8e46 4011e579ff 5bc31372c2 9e3b738f26 be9107a50b ec9b64fa4c 4b764c1b1b 398d5eb619 7da34c14c0 6a1db5f4c7", "name": "sync.FetchWrker"}
2021-06-15T14:51:28.528-0400	WARN	99a8a.sync         	item was not in response	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "hash": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "name": "sync"}
2021-06-15T14:51:28.528-0400	INFO	99a8a.sync         .FetchWrker   	send fetch request	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "peer_id": "8UG3ms3fjEUEMRisgS8CDEBZYNoaW4N1odUw8YAwuNjn", "type": "Tx", "ids": "14719c0f85 08f2bc035b 3f75cdc744 5b3fcc2f7b 5a35c36772 f5a9c6df99 ebec88c56f 2787b13183 3c2ca92b9b 38d444f3f8 beb8944a2e 28fb3976b5 15c1110300 c58d0f9efb c09078e6a0 c4bfaf8343 9b0ac06b45 d9ea2e855f 4011e579ff 5bc31372c2 00b63c8e46 4b764c1b1b 398d5eb619 7da34c14c0 6a1db5f4c7 9e3b738f26 be9107a50b ec9b64fa4c d6bfc7fcdb 11269d5a72 bb87ab2796 1bef16b3f2 d991305e3f 169f3df4ec 520e01ae1a 1ad3da43f7 2c6ce6556b fac5ab2617 e11287d570 db81af0191 d60e55fc8a f3ffd9e29e cbc9dbebc2 892ae0d8ef 8eecbcbfce 15bd3ee022 979b3bce73 a661973699 fc199dc2c1 3d229cd74d 63760769bf 25a4455fae 6700621f84 d72dcf13e9 229cd97cda c479e8d719 a7ba798b29 a04496cbae ba1c81b46a 07c1c7f786 d02a0695f6 7552cc4ef8 4933b686fd ad495d5077 f1e3a62f48 518aed2a86 41d021a83b 6344b173c0 79f927fc8b d0f152f0ab f9d02cb438 714240d584 c6bb2a2a5a", "name": "sync.FetchWrker"}
2021-06-15T14:51:28.615-0400	INFO	99a8a.sync         .FetchWrker   	peer responded to fetch request	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "peer_id": "8UG3ms3fjEUEMRisgS8CDEBZYNoaW4N1odUw8YAwuNjn", "type": "Tx", "ids": "14719c0f85 08f2bc035b 3f75cdc744 5b3fcc2f7b 5a35c36772 f5a9c6df99 ebec88c56f 2787b13183 3c2ca92b9b 38d444f3f8 beb8944a2e 28fb3976b5 15c1110300 c58d0f9efb c09078e6a0 c4bfaf8343 9b0ac06b45 d9ea2e855f 4011e579ff 5bc31372c2 00b63c8e46 4b764c1b1b 398d5eb619 7da34c14c0 6a1db5f4c7 9e3b738f26 be9107a50b ec9b64fa4c d6bfc7fcdb 11269d5a72 bb87ab2796 1bef16b3f2 d991305e3f 169f3df4ec 520e01ae1a 1ad3da43f7 2c6ce6556b fac5ab2617 e11287d570 db81af0191 d60e55fc8a f3ffd9e29e cbc9dbebc2 892ae0d8ef 8eecbcbfce 15bd3ee022 979b3bce73 a661973699 fc199dc2c1 3d229cd74d 63760769bf 25a4455fae 6700621f84 d72dcf13e9 229cd97cda c479e8d719 a7ba798b29 a04496cbae ba1c81b46a 07c1c7f786 d02a0695f6 7552cc4ef8 4933b686fd ad495d5077 f1e3a62f48 518aed2a86 41d021a83b 6344b173c0 79f927fc8b d0f152f0ab f9d02cb438 714240d584 c6bb2a2a5a", "name": "sync.FetchWrker"}
2021-06-15T14:51:28.615-0400	INFO	99a8a.sync         .txFetchQueue 	attempting to fetch objects	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "worker_num": 0, "requestId": "cf218953-fa28-4404-8f71-6a12d7485534", "sessionId": "b3b15778-4966-457c-a57a-f0b762fb87db", "type": "Tx", "ids": "14719c0f85 518aed2a86 ebec88c56f 4011e579ff e11287d570 f9d02cb438 c58d0f9efb bb87ab2796 a7ba798b29 08f2bc035b 07c1c7f786 892ae0d8ef c09078e6a0 a04496cbae 2787b13183 d72dcf13e9 41d021a83b d02a0695f6 6344b173c0 1bef16b3f2 db81af0191 79f927fc8b d991305e3f 8eecbcbfce 7552cc4ef8 fc199dc2c1 5bc31372c2 15bd3ee022 d0f152f0ab c4bfaf8343 3c2ca92b9b 9b0ac06b45 4933b686fd 979b3bce73 00b63c8e46 d60e55fc8a f3ffd9e29e 7da34c14c0 169f3df4ec f1e3a62f48 3d229cd74d 63760769bf ba1c81b46a cbc9dbebc2 6a1db5f4c7 5a35c36772 25a4455fae 9e3b738f26 be9107a50b ec9b64fa4c 4b764c1b1b f5a9c6df99 38d444f3f8 714240d584 520e01ae1a ad495d5077 398d5eb619 d9ea2e855f 229cd97cda 1ad3da43f7 beb8944a2e d6bfc7fcdb c479e8d719 2c6ce6556b fac5ab2617 c6bb2a2a5a 3f75cdc744 a661973699 11269d5a72 15c1110300 6700621f84 5b3fcc2f7b 28fb3976b5", "name": "sync.txFetchQueue"}
2021-06-15T14:51:28.615-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:51:28.615-0400	DEBUG	99a8a.sync         .txFetchQueue 	invalidated 07c1c7f786 true	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync"}
2021-06-15T14:51:28.616-0400	DEBUG	99a8a.sync         	found tx in tx pool	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "module": "sync", "layer_id": 1242, "requestId": "cf218953-fa28-4404-8f71-6a12d7485534", "channel": "newBlock", "sessionId": "4f362abb-5b35-4c86-ae4f-a01dbbacfe50", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "name": "sync"}
2021-06-15T14:51:28.646-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": false, "name": ""}
2021-06-15T14:53:52.215-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.215-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.243-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.243-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.265-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.265-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.292-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.292-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.314-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.314-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.344-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.344-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.381-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.381-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.428-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.428-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.469-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.469-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
2021-06-15T14:53:52.523-0400	WARN	99a8a.state        	failed to apply transaction	{"node_id": "99a8aebedb89e2ff64de0879ed245a4eda28e7d39423e750a62fcc07d61a12fd", "tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "errmsg": "incorrect nonce", "name": "state"}
2021-06-15T14:53:52.523-0400	INFO	00000.defaultLogger	about to report tx validity updates	{"tx_id": "07c1c7f786f0a3eda328c8d67c1eaede6acaac0a34bb9a24290e5f84af1ea03e", "validity": true, "name": ""}
```

**Comment by lrettig** [comment]
These transactions appear to be invalid (e.g., bad nonce). Questions:

- it appears that some nodes think a tx is valid, others think it's invalid, why? We appear to have a(nother) state root fork, likely related. It's unclear whether bad txs are the cause or the result of a fork (possibly both).
- how did they end up in a block in the first place? (possibly many conflicting txs with the same nonce)
- once in a block, why aren't they added to the database for at least some nodes?
- why did a few managed miners (~10) crash, but the others didn't?
