### ISSUE TITLE
Occasional panic on shutdown

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2648]
## Description

I shut down a node running locally and got a panic while shutting down. After restarting, I wasn't able to reproduce it

## Steps To Reproduce
1. Start a node
2. Wait some time
3. Press Ctrl-C
4. The error may appear

## Expected Behavior

No panic

## Environment
Please complete the following information:
 - OS: 
 
macOS 11
 - Node Version: 
 
`v0.0.0-unreleased+33c175d4cbae624b4c9de9b5879fec781f305fa0`
 - App Version (if applicable): 
 
N/A

## Additional Resources 

```
2021-08-09T18:31:10.490+0300	INFO	d1599.fetcher      	remote peer requested non existing hash	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "fetcher", "sessionId": "6810e1d0-7f2d-4e16-9d56-f7b26883fdc9", "hash": "ba3c42a73d", "hint": "IVDB", "errmsg": "leveldb: not found", "name": "fetcher"}
2021-08-09T18:31:10.676+0300	INFO	d1599.fetcher      	remote peer requested non existing hash	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "fetcher", "sessionId": "6810e1d0-7f2d-4e16-9d56-f7b26883fdc9", "hash": "ba3c42a73d", "hint": "IVDB", "errmsg": "leveldb: not found", "name": "fetcher"}
2021-08-09T18:31:10.740+0300	INFO	d1599.fetcher      	remote peer requested non existing hash	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "fetcher", "sessionId": "6810e1d0-7f2d-4e16-9d56-f7b26883fdc9", "hash": "ba3c42a73d", "hint": "IVDB", "errmsg": "leveldb: not found", "name": "fetcher"}
^C2021-08-09T18:31:11.179+0300	INFO	d1599.app          	Received an interrupt, stopping services...
	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.179+0300	INFO	d1599.p2p          	shutting down protocol	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D", "protocol": "/udp/v2/discovery", "name": "p2p"}
2021-08-09T18:31:11.179+0300	INFO	d1599.layerFetcher 	shutting down protocol	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "layerFetcher", "protocol": "/layers/2.0/", "name": "layerFetcher"}
2021-08-09T18:31:11.179+0300	ERROR	d1599.p2p          	propagate event loop stopped: protocol shutdown	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D", "sessionId": "06df3fee-daef-4b3c-97ce-b22ba7ea9839"}
2021-08-09T18:31:11.179+0300	INFO	d1599.fetcher      	shutting down protocol	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "fetcher", "protocol": "/sync/2.0/", "name": "fetcher"}
2021-08-09T18:31:11.179+0300	ERROR	d1599.p2p          	addrbook refresh error	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D", "errmsg": "bootstrap canceled by signal", "name": "p2p"}
2021-08-09T18:31:11.179+0300	WARN	d1599.p2p          	needs 6 more peers	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D"}
2021-08-09T18:31:11.179+0300	INFO	d1599.p2p          	priority queue was closed, exiting	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D", "sessionId": "06df3fee-daef-4b3c-97ce-b22ba7ea9839", "errmsg": "the queue is closed", "name": "p2p"}
2021-08-09T18:31:11.180+0300	INFO	00000.defaultLogger	app cleanup starting...
2021-08-09T18:31:11.180+0300	INFO	00000.defaultLogger	stopping grpc service
2021-08-09T18:31:11.181+0300	INFO	00000.defaultLogger	Stopping new grpc server...
2021-08-09T18:31:11.181+0300	INFO	d1599.app          	closing block producer	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.183+0300	INFO	d1599.blockBuilder 	database closed	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "blockBuilder", "file": "/Users/nkryuchkov/spacemesh/20/builder", "name": "blockBuilder"}
2021-08-09T18:31:11.183+0300	INFO	d1599.app          	closing clock	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.183+0300	INFO	d1599.clock        	closing clock 0xc0000be900	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2"}
2021-08-09T18:31:11.183+0300	INFO	d1599.clock        	closed clock 0xc0000be900	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2"}
2021-08-09T18:31:11.183+0300	INFO	d1599.app          	Stopping tortoise beacon...	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.183+0300	INFO	d1599.tBeacon      	Closing TORTOISE_BEACON_PROTOCOL	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "tBeacon"}
2021-08-09T18:31:11.183+0300	INFO	d1599.app          	closing poet listener	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.183+0300	INFO	d1599.app          	closing atx builder	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.183+0300	INFO	d1599.app          	closing hare	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.184+0300	INFO	d1599.app          	closing p2p	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "app"}
2021-08-09T18:31:11.184+0300	INFO	d1599.p2p          	Address manager shutting down	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D"}
2021-08-09T18:31:11.184+0300	INFO	d1599.hare         	broker exiting	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "hare"}
2021-08-09T18:31:11.184+0300	INFO	d1599.hare         	priority queue was closed, exiting	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "hare", "protocol": "HARE_PROTOCOL_broker", "sessionId": "bffc2663-b381-423e-ae2b-c8f44b28958e", "latest_layer": 11, "errmsg": "the queue is closed", "name": "hare"}
2021-08-09T18:31:11.184+0300	INFO	d1599.poetListener 	listening stopped	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "poetListener"}
2021-08-09T18:31:11.189+0300	ERROR	d1599.p2p          .udpnet       	listen udp error, stopping server	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "p2p", "p2pid": "83VdmNkSgdiJ63DqPyojr4Gu5ZUJ4SMn3a192U3LoM8D", "errmsg": "read udp [::]:7513: use of closed network connection", "name": "p2p.udpnet"}
2021-08-09T18:31:11.192+0300	INFO	d1599.timesync     	starting time sync round with peers	{"node_id": "d1599f8566555276993fb7bb2f078d2b87d8e1c3879ddf26d386ba3c96b1e8a2", "module": "timesync", "round": 12, "peers_count": 3, "errors_count": 0, "name": "timesync"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x49d8fda]

goroutine 155 [running]:
github.com/spacemeshos/go-spacemesh/p2p.(*Switch).sendMessageImpl(0xc0003c6000, 0x4dbc118, 0xc005837800, 0x0, 0x0, 0x4c58e70, 0xe, 0x4da5300, 0xc005837860, 0x5161001, ...)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/p2p/switch.go:351 +0x3a
github.com/spacemeshos/go-spacemesh/p2p.(*Switch).SendWrappedMessage(0xc0003c6000, 0x4dbc118, 0xc005837800, 0x0, 0x0, 0x4c58e70, 0xe, 0xc005837860, 0x4c4e72b, 0x3)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/p2p/switch.go:336 +0x90
github.com/spacemeshos/go-spacemesh/p2p/server.(*MessageServer).SendRequest(0xc0001b32c0, 0x4dbc0e0, 0xc005837800, 0x7, 0xc00584c7c0, 0x8, 0x40, 0x0, 0x0, 0xc005837770, ...)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/p2p/server/msgserver.go:278 +0x5ab
github.com/spacemeshos/go-spacemesh/timesync/peersync.(*Sync).GetOffset(0xc000232f00, 0x4dbc0e0, 0xc005166ea0, 0xc, 0xc005010630, 0x3, 0x3, 0x3, 0x0, 0xc0001c9980)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/timesync/peersync/sync.go:291 +0x499
github.com/spacemeshos/go-spacemesh/timesync/peersync.(*Sync).run(0xc000232f00, 0x4dbc070, 0xc0002b4480, 0x0, 0x0)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/timesync/peersync/sync.go:229 +0x585
github.com/spacemeshos/go-spacemesh/timesync/peersync.(*Sync).Start.func1.1(0x4dbc070, 0xc0002b4480, 0xc000032f60, 0xc000032f90)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/timesync/peersync/sync.go:186 +0x3e
github.com/spacemeshos/go-spacemesh/taskgroup.(*Group).Go.func1(0xc000434dc0, 0xc000433630)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/taskgroup/group.go:63 +0x71
created by github.com/spacemeshos/go-spacemesh/taskgroup.(*Group).Go
	/Users/nkryuchkov/GolandProjects/go-spacemesh/taskgroup/group.go:61 +0xea
```

**Comment by dshulyak** [comment]
Looks like my recent code is on the path, i will take a look.

**Comment by antonlerner** [comment]
looks like timesync is not lcosing properly or not in order (timesync should be closed before P2P since it is using it)

**Comment by dshulyak** [comment]
thanks that was the case. added small change to already opened pr
