### ISSUE TITLE
Panic peers not found in fetcher (syncer)

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2658]
## Description

One of the node in the current devne panicked with:

```
panic: cannot send fetch - no peers found

goroutine 241 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0091ba210, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x55f
go.uber.org/zap.(*SugaredLogger).log(0xc04b7c15c8, 0x804, 0x10fcb2e, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000380ae0, 0x0, 0x0, 0x10fcb2e, 0x22, 0x0, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/log/zap.go:46 +0x277
github.com/spacemeshos/go-spacemesh/log.Panic(...)
	/go/src/github.com/spacemeshos/go-spacemesh/log/log.go:146
github.com/spacemeshos/go-spacemesh/fetch.GetRandomPeer(0x1b931e0, 0x0, 0x0, 0x0, 0xc04b7c17e4)
	/go/src/github.com/spacemeshos/go-spacemesh/fetch/fetch.go:172 +0xc8
github.com/spacemeshos/go-spacemesh/layerfetcher.(*Logic).GetEpochATXs(0xc0000d8200, 0x124db60, 0xc0324346f0, 0x3e9, 0x1, 0x124db60)
	/go/src/github.com/spacemeshos/go-spacemesh/layerfetcher/layers.go:508 +0x148
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).getATXs(0xc00017c900, 0x124db60, 0xc0324346f0, 0xc000001779, 0xc0603a0a80, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:403 +0x2e5
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).syncLayer(0xc00017c900, 0x124daa0, 0xc0000a7700, 0x1779, 0xc0000a7700, 0xfa9b, 0xc00d1e98c0)
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:354 +0xac
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).synchronize(0xc00017c900, 0x124daa0, 0xc0000a7700, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:285 +0x825
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).Start.func1()
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:164 +0x8a
sync.(*Once).doSlow(0xc00017c958, 0xc000163f48)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).Start(0xc00017c900, 0x124daa0, 0xc0000a7700)
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:154 +0x7e
github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).startSyncer(0xc00030e420, 0x124daa0, 0xc0000a7700)
	/go/src/github.com/spacemeshos/go-spacemesh/cmd/node/node.go:1005 +0x7a
created by github.com/spacemeshos/go-spacemesh/cmd/node.(*SpacemeshApp).startServices
	/go/src/github.com/spacemeshos/go-spacemesh/cmd/node/node.go:754 +0x7b
```

## Expected Behavior

No panic if peers got disconnected for some reason.
Maybe we can make use of recently merged method to wait for peers https://github.com/spacemeshos/go-spacemesh/blob/develop/p2p/peers/peers.go#L103.

**Comment by dshulyak** [comment]
cc @countvonzero

**Comment by dshulyak** [comment]
It was fixed at some point
