### ISSUE TITLE
Panic baseblock is not found in multiple miners

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2659]
## Description

Tortoise crashed with:

```
panic: error processing block c9255f97d7: baseblock layer not found 65f2dd7c07, 6007

goroutine 263 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc035c1c0b0, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x55f
go.uber.org/zap.(*SugaredLogger).log(0xc04845c8a8, 0x604, 0xc031823360, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000400240, 0x0, 0x0, 0xc031823360, 0x4d, 0x0, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/log/zap.go:46 +0x277
github.com/spacemeshos/go-spacemesh/log.Panic(...)
	/go/src/github.com/spacemeshos/go-spacemesh/log/log.go:146
github.com/spacemeshos/go-spacemesh/tortoise.(*turtle).HandleIncomingLayer(0xc00052d260, 0xc074720c40, 0x155200001552)
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/verifying_tortoise.go:468 +0x4d2
github.com/spacemeshos/go-spacemesh/tortoise.(*ThreadSafeVerifyingTortoise).HandleIncomingLayer(0xc0000115a0, 0xc074720c40, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/verifying_algorithm.go:84 +0x94
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc0004d9d80, 0xc074720c40)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:284 +0xcd
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).HandleValidatedLayer(0xc000339340, 0x124db60, 0xc0000ad7d0, 0xc000001778, 0xc076eab2c0, 0x18, 0x18)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:404 +0x649
github.com/spacemeshos/go-spacemesh/hare.(*Hare).collectOutput(0xc0003572c0, 0x124db60, 0xc0000ad7d0, 0x124e6a0, 0xc074720a80, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:172 +0x224
github.com/spacemeshos/go-spacemesh/hare.(*Hare).outputCollectionLoop(0xc0003572c0, 0x124db60, 0xc0000ad7d0)
	/go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:319 +0x766
created by github.com/spacemeshos/go-spacemesh/hare.(*Hare).Start
	/go/src/github.com/spacemeshos/go-spacemesh/hare/hare.go:359 +0x7fe
```

6007 wasn't received by mesh by multiple miners (including miners 12, 17, 28 that are crashed later). 
Hare didn't run for multiple miners in between layers 6003-6007.

## Steps To Reproduce

Three miners crashed with this error in current devnet.

## Expected Behavior

In my opinion, we shouldn't run any consensus code if we suspect that we are not in sync. If we receive a layer 6008 with blocks and we can't find a base block in our database this is a clear sign that we are not in sync. Therefore we should wait until we are synced.

**Comment by dshulyak** [comment]
The panic, in this case, was removed some time ago. The tortoise still won't be able to make progress if out of order layers are received, but this is tracked in separate issues.
