### ISSUE TITLE
flaky test: panic: Log in goroutine after TestSpacemeshApp_P2PInterface has completed

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2822]
## Description

https://github.com/spacemeshos/go-spacemesh/runs/3690378536?check_suite_focus=true

```
2021-09-23T16:44:06.3382341Z panic: Log in goroutine after TestSpacemeshApp_P2PInterface has completed
2021-09-23T16:44:06.3383339Z 
2021-09-23T16:44:06.3384202Z goroutine 903 [running]:
2021-09-23T16:44:06.3385229Z testing.(*common).logDepth(0xc005748a80, 0xc0002f8e70, 0xa1, 0x3)
2021-09-23T16:44:06.3386971Z 	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:755 +0x5df
2021-09-23T16:44:06.3388522Z testing.(*common).log(...)
2021-09-23T16:44:06.3389915Z 	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:737
2021-09-23T16:44:06.3391452Z testing.(*common).Logf(0xc005748a80, 0x118500f, 0x2, 0xc00528e000, 0x1, 0x1)
2021-09-23T16:44:06.3406756Z 	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:783 +0x7e
2021-09-23T16:44:06.3408263Z go.uber.org/zap/zaptest.testingWriter.Write(0x7fc05884c8b8, 0xc005748a80, 0xc000013e00, 0xc00da5d000, 0xa2, 0x400, 0xc0004b2160, 0xfc1520, 0xc00d471ff0)
2021-09-23T16:44:06.3409631Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/zaptest/logger.go:130 +0x123
2021-09-23T16:44:06.3410780Z go.uber.org/zap/zapcore.(*ioCore).Write(0xc00d45dfb0, 0x2, 0xc04b499593a41bac, 0x39f873dd3, 0x1a6d4a0, 0x0, 0x0, 0x11b85b1, 0x2c, 0x0, ...)
2021-09-23T16:44:06.3411923Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/core.go:90 +0x106
2021-09-23T16:44:06.3412749Z go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002a3ad0, 0xc008eff080, 0x2, 0x2)
2021-09-23T16:44:06.3413994Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:216 +0x12d
2021-09-23T16:44:06.3414733Z go.uber.org/zap.(*Logger).Error(0xc00d45ff80, 0x11b85b1, 0x2c, 0xc008eff080, 0x2, 0x2)
2021-09-23T16:44:06.3415821Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/logger.go:203 +0x85
2021-09-23T16:44:06.3417525Z github.com/spacemeshos/go-spacemesh/log.FieldLogger.Error(0xc00d45ff80, 0x0, 0x0, 0x11b85b1, 0x2c, 0xc00da17cf0, 0x1, 0x1)
2021-09-23T16:44:06.3418745Z 	/home/runner/work/go-spacemesh/go-spacemesh/log/zap.go:239 +0x1d0
2021-09-23T16:44:06.3421908Z github.com/spacemeshos/go-spacemesh/p2p/net.(*Net).accept(0xc00d46c1c0, 0x130c280, 0xc000042128, 0x1307c40, 0xc00d47d120, 0xc00db1a0c0)
2021-09-23T16:44:06.3423674Z 	/home/runner/work/go-spacemesh/go-spacemesh/p2p/net/network.go:310 +0xadf
2021-09-23T16:44:06.3425738Z created by github.com/spacemeshos/go-spacemesh/p2p/net.(*Net).Start
2021-09-23T16:44:06.3426741Z 	/home/runner/work/go-spacemesh/go-spacemesh/p2p/net/network.go:125 +0x36b
```

**Comment by moshababo** [comment]
Obsolete.
