### ISSUE TITLE
flaky test: panic: Log in goroutine after TestTortoiseBeacon has completed

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2874]
## Description

https://github.com/spacemeshos/go-spacemesh/runs/3893699317

```
panic: Log in goroutine after TestTortoiseBeacon has completed

goroutine 212 [running]:
testing.(*common).logDepth(0xc000181680, 0xc0033a8d20, 0x4e, 0x3)
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:755 +0x5df
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:737
testing.(*common).Logf(0xc000181680, 0x774010, 0x2, 0xc0033c8830, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:783 +0x7e
go.uber.org/zap/zaptest.testingWriter.Write(0x7ff7e4406a98, 0xc000181680, 0xc000012600, 0xc0033cb000, 0x4f, 0x400, 0xc00000e160, 0x7040c0, 0xc0033c8820)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/zaptest/logger.go:130 +0x123
go.uber.org/zap/zapcore.(*ioCore).Write(0xc002d36330, 0x0, 0xc05221a909fcd425, 0x9053531c, 0x9a5a60, 0xc0022da500, 0xd, 0xc0032ad770, 0x22, 0x0, ...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/core.go:90 +0x106
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00010c420, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:216 +0x12d
go.uber.org/zap.(*SugaredLogger).log(0xc000145b60, 0x0, 0x77bb90, 0x18, 0xc000145c80, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Infof(...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:138
github.com/spacemeshos/go-spacemesh/log.Log.Info(0xc000667f80, 0x7746e9, 0x5, 0x77bb90, 0x18, 0xc000145c80, 0x1, 0x1)
	/home/runner/work/go-spacemesh/go-spacemesh/log/zap.go:25 +0x114
github.com/spacemeshos/go-spacemesh/timesync.(*TimeClock).startClock(0xc002d40060)
	/home/runner/work/go-spacemesh/go-spacemesh/timesync/clock.go:75 +0xc48
created by github.com/spacemeshos/go-spacemesh/timesync.NewClock
	/home/runner/work/go-spacemesh/go-spacemesh/timesync/clock.go:47 +0x205
```

**Comment by nkryuchkov** [comment]
https://github.com/spacemeshos/go-spacemesh/runs/3914801032

**Comment by moshababo** [comment]
Obsolete.
