### ISSUE TITLE
fetcher: panic in layerfetcher.(*Logic).fetchLayerBlocks 

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2887]
devnet208 miner-22

```
{"L":"WARN","T":"2021-10-22T04:08:21.419-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"vDR8cJt2nH9np6urUGg9ikVJhTSNQL2D6LjLBbCCM8C","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:21.470-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"EPe76RbTm5XULrMDspyGfAMcUt3Ynqkyumz2L5Q3kcpG","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:21.520-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"6h5iSHsiGmTqukbq4fs13qdJkbgyZh1wtYG9SsRdL2p5","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:21.570-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"A14xfHQTqz6BvL5uCd3ZskKNoSdtSFk1Hu9XtLYn1Thp","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:21.620-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"6h5iSHsiGmTqukbq4fs13qdJkbgyZh1wtYG9SsRdL2p5","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:21.670-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"HJV94rwfZjxaSNjAUb7G11uymE1B3KnjmH38qLMVmeB5","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:21.720-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"2Q1wEvtHZZpDb2ZAyzgKKwvPzgfWNE79t3qC3oRfehfz","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:22.006-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"9qbeU22Y7mMy2wAxA2PsaRZqkS2EVnYWZBAdxSmNWT2J","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:22.019-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"2Q1wEvtHZZpDb2ZAyzgKKwvPzgfWNE79t3qC3oRfehfz","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:22.070-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"YhZG2aYoU98HmYSVkwBfJs5PN138PkiS4xnvXEKXp7k","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:22.120-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"3VWXdkSQKPUpdf85LMPGD24V2HujtM9Er7grMAE9dApN","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:22.170-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"HeNZpbkg87fadxnxhDF5hkfeMixJqb1i3tNfNSAPSnrU","name":"fetcher"}
{"L":"WARN","T":"2021-10-22T04:08:24.118-0400","N":"6f821.fetcher      ","M":"hash not found in response from peer","node_id":"6f821ba8c0d45033c1005f488af30822cacb7ff665c143cb5c2bfa41e43b0654","module":"fetcher","hint":"ATXDB","hash":"5a275d972a","peer":"7JtG25gwU5QDRPX2pka4GEg6XMQPYDCYTBPZ1uqsWt2c","name":"fetcher"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc76c8d]

goroutine 19812263 [running]:
github.com/spacemeshos/go-spacemesh/layerfetcher.(*Logic).fetchLayerBlocks(0xc000123040, 0x12830a0, 0xc02ba0e1e0, 0x686, 0xc01663fd00, 0x3bc, 0x3bc)
	/go/src/github.com/spacemeshos/go-spacemesh/layerfetcher/layers.go:289 +0x38d
github.com/spacemeshos/go-spacemesh/layerfetcher.(*Logic).receiveLayerContent(0xc000123040, 0x12830a0, 0xc02ba0e1e0, 0x686, 0x7f53b9cac310, 0xc017e7a1e0, 0x1a, 0xc014dd0400, 0x3bc, 0x3bc, ...)
	/go/src/github.com/spacemeshos/go-spacemesh/layerfetcher/layers.go:335 +0xadd
github.com/spacemeshos/go-spacemesh/layerfetcher.(*Logic).PollLayerContent.func1(0xc014dd0400, 0x3bc, 0x3bc)
	/go/src/github.com/spacemeshos/go-spacemesh/layerfetcher/layers.go:269 +0x8b
github.com/spacemeshos/go-spacemesh/p2p/server.(*MessageServer).handleResponseMessage(0xc00017b2c0, 0x12830a0, 0xc000202540, 0xc006e41950)
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/server/msgserver.go:296 +0x56c
github.com/spacemeshos/go-spacemesh/p2p/server.(*MessageServer).handleMessage(0xc00017b2c0, 0x12830a0, 0xc000202540, 0x7f53b9cac410, 0xc006e41b30)
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/server/msgserver.go:250 +0xbc
github.com/spacemeshos/go-spacemesh/p2p/server.(*MessageServer).readLoop.func2(0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/p2p/server/msgserver.go:188 +0x85
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00017b330, 0xc032127aa0)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
```

**Comment by countvonzero** [comment]
@dshulyak 
i cannot figure out how this could happen. do you have a theory?

**Comment by dshulyak** [comment]
I don't see anything wrong with the fetcher part as well.
It is possible to get this if a callback (in this case receiveLayerContent) is called several times for a single request. I had a similar crash while i was working on libp2p integration, but that was fixed in my branch.

Maybe there was some bug in the previous server that could invoke the callback (or send a response) multiple times per peer.

**Comment by moshababo** [comment]
Outdated.
