### ISSUE TITLE
Logger doesn't log fields on panic

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2947]
## Description

Logger doesn't log fields on panic. 

Example: https://github.com/spacemeshos/go-spacemesh/issues/2937. 

The node panicked with no logged fields:
```
panic: tried to update a previous layer

goroutine 1200 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001b0840, {0xc0034f66c0, 0x3, 0x3})
	/Users/nkryuchkov/go/pkg/mod/go.uber.org/zap@v1.19.0/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*Logger).Panic(0xc00d36ddc0, {0x4d6276a, 0x0}, {0xc0034f66c0, 0x3, 0x3})
	/Users/nkryuchkov/go/pkg/mod/go.uber.org/zap@v1.19.0/logger.go:230 +0x59
github.com/spacemeshos/go-spacemesh/log.FieldLogger.Panic({0xc00a26e000, {0x4d3d947, 0x4ff1c20}}, {0x4d6276a, 0x20}, {0xc00326f6e8, 0x2, 0x2})
	/Users/nkryuchkov/GolandProjects/go-spacemesh/log/zap.go:258 +0x1b9
github.com/spacemeshos/go-spacemesh/hare.(*Broker).updateLatestLayer(0xc00041f100, {0x500e0b8, 0xc0085ae390}, {0x0})
	/Users/nkryuchkov/GolandProjects/go-spacemesh/hare/broker.go:341 +0x272
github.com/spacemeshos/go-spacemesh/hare.(*Broker).Register.func1()
	/Users/nkryuchkov/GolandProjects/go-spacemesh/hare/broker.go:405 +0x8c
github.com/spacemeshos/go-spacemesh/hare.(*Broker).eventLoop(0xc00041f100, {0x500e0b8, 0xc009723dd0})
	/Users/nkryuchkov/GolandProjects/go-spacemesh/hare/broker.go:332 +0x4fc
created by github.com/spacemeshos/go-spacemesh/hare.(*Broker).Start
	/Users/nkryuchkov/GolandProjects/go-spacemesh/hare/broker.go:97 +0x131
```

However, [it should also log](https://github.com/spacemeshos/go-spacemesh/blob/develop/hare/broker.go#L341) fields, which are very useful for debugging a panic:
```
b.WithContext(ctx).With().Panic("tried to update a previous layer",
	log.FieldNamed("this_layer", id),
	log.FieldNamed("prev_layer", b.getLatestLayer()))
```

We have a lot of such code now and it wouldn't work as we expect on panic.

**Comment by dshulyak** [comment]
Weird, i do see fields in PANIC log. Note that there should be an actual log before stack trace

```
logger.go:130: 2021-11-29T08:35:02.734+0200	PANIC	70b17.trtl         	failed to recover ballot weights	{"node_id": "70b17bc84711cb05399bbc7fe07a48a505a3753e07c41b73bd86e90a1454bf9a", "module": "trtl", "errmsg": "ref ballot 5effa86158 for 628ea7bdc5 is unknown", "name": "trtl"}
```

**Comment by nkryuchkov** [comment]
@dshulyak I don't know where I was looking and how I could not see that an actual log is present. I apologize!
