### ISSUE TITLE
tortoise, mesh: handle the case when verified layer didn't reach historically verified layer during rerun

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#3060]
during rerun we track if opinion on blocks has changed, and if it did we will notify mesh to revert the state. this doesn't cover the case when we failed to decide on blocks that were previously decided. this could happen because during rerun we count votes from all known layers. 

this caused miner-11 to crash with the following exception, in short applied state was layer 2517, but according to the tortoise latest verified was 2516. which effectively went backward, and this is only expected by mesh if the revert is true.

```
{"L":"PANIC","T":"2022-01-18T01:40:29.803-0500","N":"26605.mesh         ","M":"update state out-of-order","node_id":"26605f4fb2c89bef0d1fcc6165b54234736eeca8e4ba947643a953332c5f8e42","module":"mesh","sessionId":"62989d20-a9a1-4b6c-b663-25d037b242d1","verified":2516,"latest":2517,"name":"mesh"}
panic: update state out-of-order

goroutine 2660 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc007d980c0, 0xc005f70300, 0x3, 0x3)
	/go/pkg/mod/go.uber.org/zap@v1.19.0/zapcore/entry.go:232 +0x51f
go.uber.org/zap.(*Logger).Panic(0xc00c7150e0, 0x13e7a34, 0x19, 0xc005f70300, 0x3, 0x3)
	/go/pkg/mod/go.uber.org/zap@v1.19.0/logger.go:230 +0x85
github.com/spacemeshos/go-spacemesh/log.FieldLogger.Panic(0xc00c7150e0, 0x13ccac7, 0x4, 0x13e7a34, 0x19, 0xc00f4476c8, 0x2, 0x2)
	/go/src/github.com/spacemeshos/go-spacemesh/log/zap.go:288 +0x1d0
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).updateStateWithLayer(0xc0005bab40, 0x16a0d20, 0xc00c79ad50, 0xc0000009d4, 0xc005d473b0, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:593 +0x3e5
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).pushLayer(0xc0005bab40, 0x16a0d20, 0xc00c79ad50, 0x9d4, 0x17, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:460 +0x2d4
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).pushLayersToState(0xc0005bab40, 0x16a0d20, 0xc00c79ad50, 0x9d4000009d4, 0x10, 0xc00f447c58)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:427 +0x4ac
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ProcessLayer(0xc00026a318, 0x16a0d20, 0xc00c79ad50, 0x9d7, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:326 +0x57f
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).validateLayer(0xc0005057a0, 0x16a0d20, 0xc00c79ad50, 0x9d7, 0x0, 0x0)
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:567 +0x179
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).startValidating.func1(0xc009f672d4, 0xc009f672d4)
	/go/src/github.com/spacemeshos/go-spacemesh/syncer/syncer.go:544 +0x1c5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000505888, 0xc00df30c60)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Comment by dshulyak** [comment]
```
{"L":"INFO","T":"2022-01-27T07:08:04.087-0500","N":"571e2.mesh         ","M":"saving hare output for layer","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","layer_id":3099,"block_id":"1beaca41c0"}
{"L":"INFO","T":"2022-01-27T07:08:04.089-0500","N":"571e2.mesh         ","M":"processing layer","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","layer_id":3099}
{"L":"INFO","T":"2022-01-27T07:08:04.089-0500","N":"571e2.trtl         ","M":"adding layer to the state","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"trtl","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","layer_id":3099,"name":"trtl"}
{"L":"INFO","T":"2022-01-27T07:08:04.091-0500","N":"571e2.trtl         ","M":"counted weight from good ballots","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"trtl","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","layer_id":3099,"last_layer":"3099","ballots_layer":"3099","good_weight":"37","total":"84","expected":"42.33","ballots_count":37,"good_ballots_count":37,"name":"trtl"}
{"L":"INFO","T":"2022-01-27T07:08:04.091-0500","N":"571e2.trtl         ","M":"candidate layer is verified","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"trtl","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","layer_id":3099,"last_layer":"3099","verifier":"verifying","candidate_layer":"3098","margin":"37","abstained_weightError":"PANIC=runtime error: invalid memory address or nil pointer dereference","local_threshold":"8.47","global_threshold":"33.87","name":"trtl"}
{"L":"INFO","T":"2022-01-27T07:08:04.091-0500","N":"571e2.mesh         ","M":"tortoise results","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","layer_id":3099,"reverted":false,"old_verified":3097,"new_verified":3098,"name":"mesh"}
{"L":"INFO","T":"2022-01-27T07:08:04.091-0500","N":"571e2.mesh         ","M":"processed layer set","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","event":true,"layer_id":3099,"name":"mesh"}
{"L":"INFO","T":"2022-01-27T07:08:04.092-0500","N":"571e2.mesh         ","M":"pushing layers to state","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","protocol":"HARE_PROTOCOL_outputloop","sessionId":"24468d04-1af6-49d8-84b0-d9e4736efb27","from_layer":"3098","to_layer":"3098"}
{"L":"INFO","T":"2022-01-27T07:08:04.092-0500","N":"571e2.layerFetcher ","M":"request execution time","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"layerFetcher","sessionId":"11eed089-4243-410a-b8b5-8fe86f1ea3a6","protocol":"/block/1.0.0","duration":"1.341488659s","name":"layerFetcher"}
{"L":"INFO","T":"2022-01-27T07:08:04.096-0500","N":"571e2.SVM          ","M":"new state root","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"SVM","layer_id":3098,"state_root":"8e76117ee1fabee1ed873a4e7f3a9329972a9f24efba897ef9864c875d31bed5","name":"SVM"}
{"L":"INFO","T":"2022-01-27T07:08:04.097-0500","N":"571e2.SVM          ","M":"new state root","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"SVM","layer_id":3098,"state_root":"8e76117ee1fabee1ed873a4e7f3a9329972a9f24efba897ef9864c875d31bed5","name":"SVM"}
{"L":"INFO","T":"2022-01-27T07:08:04.110-0500","N":"571e2.mesh         ","M":"processing layer","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","sessionId":"11eed089-4243-410a-b8b5-8fe86f1ea3a6","layer_id":3030}
{"L":"INFO","T":"2022-01-27T07:08:04.110-0500","N":"571e2.mesh         ","M":"tortoise results","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","sessionId":"11eed089-4243-410a-b8b5-8fe86f1ea3a6","layer_id":3030,"reverted":false,"old_verified":3098,"new_verified":3098,"name":"mesh"}
{"L":"INFO","T":"2022-01-27T07:08:04.110-0500","N":"571e2.mesh         ","M":"trying to set processed layer to an older layer","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","processed":3099,"layer_id":3030,"name":"mesh"}
{"L":"INFO","T":"2022-01-27T07:08:04.110-0500","N":"571e2.mesh         ","M":"pushing layers to state","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","sessionId":"11eed089-4243-410a-b8b5-8fe86f1ea3a6","from_layer":"3098","to_layer":"3098"}
{"L":"INFO","T":"2022-01-27T07:08:04.113-0500","N":"571e2.mesh         ","M":"applied transactions","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","layer_id":3098,"valid_block_txs":0,"num_failed_txs":0,"name":"mesh"}
{"L":"INFO","T":"2022-01-27T07:08:04.114-0500","N":"571e2.mesh         ","M":"end of layer state root","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","event":true,"layer_id":3098,"state_root":"0x8e76117ee1fabee1ed873a4e7f3a9329972a9f24efba897ef9864c875d31bed5","name":"mesh"}
{"L":"PANIC","T":"2022-01-27T07:08:04.114-0500","N":"571e2.mesh         ","M":"update state out-of-order","node_id":"571e24001560015bb64046eceb2167d0c9b09760adc7aa92df0a5fa964aed903","module":"mesh","sessionId":"11eed089-4243-410a-b8b5-8fe86f1ea3a6","verified":3098,"latest":3098,"name":"mesh"}
panic: update state out-of-order

```
