### ISSUE TITLE
node unable to recover from crash

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3181]
## Description

when a node panics and restarts, it enters a crash loop with this stack trace. the cause is that block validity updater is not initialized with mesh instance when tortoise rerun starts.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe9deb9]

goroutine 676 [running]:
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).UpdateBlockValidity(0x0, {0x63, 0x42, 0x83, 0x95, 0x48, 0xfe, 0xb1, 0xa4, 0x4b, ...}, ...)
	/go/src/github.com/spacemeshos/go-spacemesh/mesh/mesh.go:144 +0x39
github.com/spacemeshos/go-spacemesh/tortoise.persistContextualValidity.func1({0x137808})
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/util.go:141 +0x387
github.com/spacemeshos/go-spacemesh/tortoise.iterateLayers({0x2c4f00}, {0xc0}, 0xc0001377c0)
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/util.go:154 +0x3a
github.com/spacemeshos/go-spacemesh/tortoise.persistContextualValidity({0xc0004d9c80, {0x123e9a8, 0xc0002c4ec0}}, {0x14f69a0, 0xc0000be2b0}, {0xbb8}, {0x0}, 0x14000003e8, 0x400000032)
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/util.go:133 +0xbe
github.com/spacemeshos/go-spacemesh/tortoise.(*turtle).processLayer(0xc00048a000, {0xc0004d9c20, {0x123e9a8, 0xc000137a40}}, {0x223b00})
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/tortoise.go:559 +0x58f
github.com/spacemeshos/go-spacemesh/tortoise.(*turtle).onLayerTerminated(0xc00048a000, {0x1515ef0, 0xc000223b00}, {0x1254bb3})
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/tortoise.go:497 +0x38c
github.com/spacemeshos/go-spacemesh/tortoise.(*Tortoise).rerun(0xc0004d6540, {0x1515ef0, 0xc000223b00})
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/rerun.go:87 +0x7ae
github.com/spacemeshos/go-spacemesh/tortoise.New.func1()
	/go/src/github.com/spacemeshos/go-spacemesh/tortoise/algorithm.go:145 +0x2a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
``` 

## Actual Behavior

crash loop

## Expected Behavior

recover and continue smeshing

## Additional Resources 

full log [log.txt](https://github.com/spacemeshos/go-spacemesh/files/8528032/log.txt)

**Comment by dshulyak** [comment]
should have been closed by linked pr, right?
