### ISSUE TITLE
crash: fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3300]
## Description

https://github.com/spacemeshos/go-spacemesh/runs/7075903106?check_suite_focus=true
```
2022-06-27 09:13:17 | /go/src/github.com/spacemeshos/go-spacemesh/fetch/fetch.go:243 +0x3aa
-- | --
  |   | 2022-06-27 09:13:17 | created by github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).handleNewRequest
  |   | 2022-06-27 09:13:17 | /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0010adfe8 sp=0xc0010adfe0 pc=0x474f41
  |   | 2022-06-27 09:13:17 | runtime.goexit()
  |   | 2022-06-27 09:13:17 | /go/src/github.com/spacemeshos/go-spacemesh/fetch/fetch.go:243 +0x26 fp=0xc0010adfe0 sp=0xc0010adfc8 pc=0xd9de46
  |   | 2022-06-27 09:13:17 | github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).handleNewRequest.func1()
  |   | 2022-06-27 09:13:17 | /go/src/github.com/spacemeshos/go-spacemesh/fetch/fetch.go:430 +0x516 fp=0xc0010adfc8 sp=0xc0010adda0 pc=0xda0896
  |   | 2022-06-27 09:13:17 | github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).requestHashBatchFromPeers(0xc0003ff800)
  |   | 2022-06-27 09:13:17 | /go/src/github.com/spacemeshos/go-spacemesh/fetch/fetch.go:441 +0x7f fp=0xc0010adda0 sp=0xc0010adcd0 pc=0xda095f
  |   | 2022-06-27 09:13:17 | github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).send(0xc0003ff890?, {0xc0010ec000, 0x16, 0x20})
  |   | 2022-06-27 09:13:17 | /go/src/github.com/spacemeshos/go-spacemesh/fetch/fetch.go:459 +0x812 fp=0xc0010adcd0 sp=0xc0010ad8e0 pc=0xda12b2
  |   | 2022-06-27 09:13:17 | github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).organizeRequests(0xc0003ff800, {0xc0010ec000, 0x16, 0x7fd5a6d0c090?})
  |   | 2022-06-27 09:13:17 | /go/src/github.com/spacemeshos/go-spacemesh/fetch/cache.go:28
  |   | 2022-06-27 09:13:17 | github.com/spacemeshos/go-spacemesh/fetch.HashPeers.ToList(...)
  |   | 2022-06-27 09:13:17 | /usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc0010ad8e0 sp=0xc0010ad870 pc=0x41992b
  |   | 2022-06-27 09:13:17 | runtime.mapiternext(0xc0010adb10?)
  |   | 2022-06-27 09:13:17 | /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0010ad870 sp=0xc0010ad840 pc=0x441f71
  |   | 2022-06-27 09:13:17 | runtime.throw({0x127f3f9?, 0x0?})
  |   | 2022-06-27 09:13:17 | goroutine 8517 [running]:
  |   | 2022-06-27 09:13:17 |  
  |   | 2022-06-27 09:13:17 | fatal error: concurrent map iteration and map write
```

**Comment by dshulyak** [comment]
Map iteration is intentionally randomized in golang. There is no need for that helper, just pick first in range.
