### ISSUE TITLE
systest: cluster panic on failure to add PoET server

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3316]
## Description

https://github.com/spacemeshos/go-spacemesh/runs/7155880853?check_suite_focus=true
```
--- FAIL: TestAddNodes (71.96s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f88bd]
goroutine 85 [running]:
testing.tRunner.func1.2({0x18b2c80, 0x298d450})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x18b2c80, 0x298d450})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/spacemeshos/go-spacemesh/systest/cluster.(*Cluster).AddPoet(0xc000691d50, 0xc000603380?)
	/build/systest/cluster/cluster.go:186 +0x15d
github.com/spacemeshos/go-spacemesh/systest/tests.TestAddNodes(0x410099?)
	/build/systest/tests/nodes_test.go:34 +0x13f
testing.tRunner(0xc000603380, 0x1bda188)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

**Comment by countvonzero** [comment]
@dshulyak @evt i believed you seen this before. was it determined to be caused by slow GKE?

**Comment by dshulyak** [comment]
i don't recall seeing it, but i can't imagine how it can be caused by slow gke

what looks off to me is that namespace got deleted before panic. the only time when it is possible is when test pod gets sigint or sigterm. i believe k8s in some cases does that for some internal management purposes

```
    logger.go:130: 2022-07-01T19:47:23.555Z	INFO	using	{"namespace": "test-rvby"}
=== CONT  TestSmeshing
    logger.go:130: 2022-07-01T19:47:23.569Z	INFO	using	{"namespace": "test-uzzf"}
=== CONT  TestAddNodes
    logger.go:130: 2022-07-01T19:48:35.425Z	INFO	namespace was deleted	{"namespace": "test-rvby"}
```

**Comment by countvonzero** [comment]
this is caused by a bug in my code where node refuses to start when genesis account is not set, which is true for the systest.
