### ISSUE TITLE
Test `TestNewNIPostBuilderNotInitialized` from `activation` pkg times out on Windows in CI

### ISSUE THREAD

**Issue by poszu** [spacemeshos/go-spacemesh#3629]
## Description
Test `TestNewNIPostBuilderNotInitialized` from `activation` pkg times out on Windows in CI

## Steps to reproduce
This test times out only in CI. It doesn't fail when I run the test locally. To reproduce, execute unit tests on CI on Windows platform.

## Actual Behavior
```sh
=== FAIL: activation TestNewNIPostBuilderNotInitialized (unknown)
panic: test timed out after 5m0s

goroutine 931 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc00027a4e0, {0x7ff6cbabe9e5?, 0x7ff6ca930e93?}, 0x7ff6cbbb0cb0)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc000269230?)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc00027a4e0, 0xc00025dc88)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0006ea000?, {0x7ff6cb487040, 0x38, 0x38}, {0xa0?, 0x26ec650ffff?, 0x7ff6cc409320?})
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0006ea000)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1719 +0x5d9
github.com/spacemeshos/go-spacemesh/activation.TestMain(0x7ff6ca9074f1?)
	D:/a/go-spacemesh/go-spacemesh/activation/activation_test.go:38 +0x35
main.main()
	_testmain.go:169 +0x1d3

goroutine 22 [select, 4 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0001ee780)
	C:/Users/runneradmin/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:71 +0x11f
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	C:/Users/runneradmin/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:36 +0xca

goroutine 900 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0x0?)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc0005144e0?)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/sync/waitgroup.go:136 +0x52
github.com/spacemeshos/poet/integration.(*server).stop(0xc000281860)
	C:/Users/runneradmin/go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220906085751-7a5dcff04063/integration/server.go:191 +0xac
github.com/spacemeshos/poet/integration.(*server).shutdown(0xc000281860, 0x1)
	C:/Users/runneradmin/go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220906085751-7a5dcff04063/integration/server.go:165 +0x25
github.com/spacemeshos/poet/integration.(*Harness).TearDown(0xc0003f7fe0, 0x40?)
	C:/Users/runneradmin/go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220906085751-7a5dcff04063/integration/harness.go:71 +0x25
github.com/spacemeshos/go-spacemesh/activation.TestNewNIPostBuilderNotInitialized.func2()
	D:/a/go-spacemesh/go-spacemesh/activation/nipost_test.go:259 +0x38
github.com/spacemeshos/go-spacemesh/activation.TestNewNIPostBuilderNotInitialized(0xc0003e7040)
	D:/a/go-spacemesh/go-spacemesh/activation/nipost_test.go:280 +0x848
testing.tRunner(0xc0003e7040, 0x7ff6cbbb0cb0)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1486 +0x35f

goroutine 54 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 44 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 729 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 51 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 840 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 785 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 60 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 559 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 63 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 634 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 445 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 860 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 574 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 653 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 656 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 605 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 629 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 552 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 568 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 815 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 807 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 797 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 869 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 828 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 498 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 822 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 506 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 831 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 836 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 764 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 720 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 698 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 889 [chan send, 4 minutes]:
github.com/spacemeshos/poet/integration.(*server).start.func1()
	C:/Users/runneradmin/go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220906085751-7a5dcff04063/integration/server.go:151 +0x1c8
created by github.com/spacemeshos/poet/integration.(*server).start
	C:/Users/runneradmin/go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220906085751-7a5dcff04063/integration/server.go:139 +0x33a

goroutine 680 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 714 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 898 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8

goroutine 890 [select, 4 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000510300)
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.50.0/balancer_conn_wrappers.go:112 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.50.0/balancer_conn_wrappers.go:73 +0x22a

goroutine 929 [chan receive, 4 minutes]:
crawshaw.io/sqlite.(*Conn).SetInterrupt.func1()
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:299 +0xac
created by crawshaw.io/sqlite.(*Conn).SetInterrupt
	C:/Users/runneradmin/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlite.go:294 +0x1f8
```

## Environment
Please complete the following information:
 - OS: Windows, CI

**Comment by fasmat** [comment]
Fixed with: https://github.com/spacemeshos/go-spacemesh/pull/3679
