### ISSUE TITLE
Flaky test: TestBootstrapEmitEvents

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#4075]
#### Description

Failed during unrelated change: https://github.com/spacemeshos/go-spacemesh/actions/runs/4231966548/jobs/7351137974

```
=== FAIL: p2p/bootstrap TestBootstrapEmitEvents (unknown)
panic: test timed out after 5m0s

goroutine 277 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.5/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc000277520, {0x10c8d46, 0x17}, 0x11b34b0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc000277520, 0xc00023fba0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x217
testing.runTests(0xc00029d4a0?, {0x18024e0, 0x3, 0x3}, {0x40?, 0x7f6c0b8ac3d8?, 0x1a7b6c0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc00029d4a0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:51 +0x2ea

goroutine 22 [chan receive, 4 minutes]:
github.com/spacemeshos/go-spacemesh/p2p/bootstrap.TestBootstrapEmitEvents(0xc0002776c0)
	/home/runner/work/go-spacemesh/go-spacemesh/p2p/bootstrap/bootstrap_test.go:68 +0x7ce
testing.tRunner(0xc0002776c0, 0x11b34b0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x75e

goroutine 23 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.(*memoryAddrBook).background(0xc000115b00, {0x1358c58, 0xc0002ca440})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/peerstore/pstoremem/addr_book.go:116 +0x1e9
created by github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.NewAddrBook
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/peerstore/pstoremem/addr_book.go:96 +0x476

goroutine 33 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*ObservedAddrManager).worker(0xc0002cc8f0)
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/obsaddr.go:258 +0x33d
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.NewObservedAddrManager
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/obsaddr.go:158 +0x837

goroutine 58 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop.func1()
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:239 +0x15a
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:235 +0x66b

goroutine 35 [select]:
github.com/libp2p/go-libp2p/p2p/host/pstoremanager.(*PeerstoreManager).background(0xc00011fa40, {0x1358c58, 0xc0002cb600}, {0x1357160, 0xc0002e4820})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/pstoremanager/pstoremanager.go:96 +0x3ed
created by github.com/libp2p/go-libp2p/p2p/host/pstoremanager.(*PeerstoreManager).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/pstoremanager/pstoremanager.go:78 +0x417

goroutine 36 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop(0xc000247200, {0x1358c58, 0xc0002cb3c0})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:249 +0x765
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:212 +0x27d

goroutine 37 [select]:
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).background(0xc000210900)
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:532 +0x305
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:373 +0xef

goroutine 38 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.(*memoryAddrBook).background(0xc000116d00, {0x1358c58, 0xc0002cb6c0})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/peerstore/pstoremem/addr_book.go:116 +0x1e9
created by github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.NewAddrBook
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/peerstore/pstoremem/addr_book.go:96 +0x476

goroutine 55 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop.func1()
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:239 +0x15a
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:235 +0x66b

goroutine 40 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*ObservedAddrManager).worker(0xc0002ccea0)
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/obsaddr.go:258 +0x33d
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.NewObservedAddrManager
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/obsaddr.go:158 +0x837

goroutine 68 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop.func1()
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:239 +0x15a
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:235 +0x66b

goroutine 42 [select]:
github.com/libp2p/go-libp2p/p2p/host/pstoremanager.(*PeerstoreManager).background(0xc0002e4a50, {0x1358c58, 0xc00071e800}, {0x1357160, 0xc0002e5720})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/pstoremanager/pstoremanager.go:96 +0x3ed
created by github.com/libp2p/go-libp2p/p2p/host/pstoremanager.(*PeerstoreManager).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/pstoremanager/pstoremanager.go:78 +0x417

goroutine 43 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop(0xc0002478c0, {0x1358c58, 0xc00071e640})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:249 +0x765
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:212 +0x27d

goroutine 44 [select]:
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).background(0xc000210a80)
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:532 +0x305
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:373 +0xef

goroutine 45 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.(*memoryAddrBook).background(0xc00072e000, {0x1358c58, 0xc00071e880})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/peerstore/pstoremem/addr_book.go:116 +0x1e9
created by github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.NewAddrBook
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/peerstore/pstoremem/addr_book.go:96 +0x476

goroutine 47 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*ObservedAddrManager).worker(0xc0002cd380)
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/obsaddr.go:258 +0x33d
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.NewObservedAddrManager
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/obsaddr.go:158 +0x837

goroutine 49 [select]:
github.com/libp2p/go-libp2p/p2p/host/pstoremanager.(*PeerstoreManager).background(0xc0002e5950, {0x1358c58, 0xc00071fa00}, {0x1357160, 0xc00074a640})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/pstoremanager/pstoremanager.go:96 +0x3ed
created by github.com/libp2p/go-libp2p/p2p/host/pstoremanager.(*PeerstoreManager).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/pstoremanager/pstoremanager.go:78 +0x417

goroutine 50 [select, 4 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).loop(0xc000247c20, {0x1358c58, 0xc00071f800})
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:249 +0x765
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*idService).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/protocol/identify/id.go:212 +0x27d

goroutine 51 [select]:
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).background(0xc000210c00)
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:532 +0x305
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).Start
	/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:373 +0xef

goroutine 60 [select]:
github.com/spacemeshos/go-spacemesh/p2p/bootstrap.(*Bootstrap).run(0xc000184ea0, {0x1358c58, 0xc00071fb00}, {0x1357160, 0xc00078d770}, {0x13557f8?, 0xc0007ac680})
	/home/runner/work/go-spacemesh/go-spacemesh/p2p/bootstrap/bootstrap.go:115 +0x76f
github.com/spacemeshos/go-spacemesh/p2p/bootstrap.NewBootstrap.func1()
	/home/runner/work/go-spacemesh/go-spacemesh/p2p/bootstrap/bootstrap.go:60 +0x9a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x87
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x12f
```

**Comment by dshulyak** [comment]
this needs to be fixed together with libp2p update
