### ISSUE TITLE
panic on node shutdown

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4318]
## Description
When using `ctrl+c` to shutdown a node connected to our testnet I'm sometimes observing panics.
```
panic: not all connections returned to Pool before timeout

goroutine 12865 [running]:
crawshaw.io/sqlite/sqlitex.(*Pool).Close(0xc000e27f40)
	/home/pierspowlesland/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20211227050848-2cdb5c1a86a1/sqlitex/pool.go:251 +0x206
github.com/spacemeshos/go-spacemesh/sql.(*Database).Close(0xc0001a0460?)
	/home/pierspowlesland/projects/go-spacemesh/sql/database.go:229 +0x1c
github.com/spacemeshos/go-spacemesh/cmd/node.(*App).stopServices(0xc00025f4a0, {0x1bd9c80?, 0xc003225bc0?})
	/home/pierspowlesland/projects/go-spacemesh/cmd/node/node.go:982 +0x4b1
github.com/spacemeshos/go-spacemesh/cmd/node.(*App).Cleanup(0xc00025f4a0, {0x1bd9c80, 0xc003225bc0})
	/home/pierspowlesland/projects/go-spacemesh/cmd/node/node.go:408 +0x279
github.com/spacemeshos/go-spacemesh/cmd/node.GetCommand.func1.1.1()
	/home/pierspowlesland/projects/go-spacemesh/cmd/node/node.go:139 +0x33
created by github.com/spacemeshos/go-spacemesh/cmd/node.GetCommand.func1.1
	/home/pierspowlesland/projects/go-spacemesh/cmd/node/node.go:138 +0x1b2
```

## Steps to reproduce
Using the following config
```json
{
  "api": {
    "grpc": [
      "debug",
      "node",
      "mesh",
      "globalstate",
      "transaction",
      "smesher"
    ]
  },
  "preset": "testnet",
  "p2p": {
    "bootnodes": [
      "/dns4/testnet-03-bootnode-0.spacemesh.network/tcp/5000/p2p/12D3KooWQMAAL9nkgXJgTM2psJLMbWRgZLjAxJozx7dNkKYczs2V",
      "/dns4/testnet-03-bootnode-1.spacemesh.network/tcp/5000/p2p/12D3KooWF2bhnqsnu2UjxJGZs8KCbzvd91vnud29KaG9rzTNFH78",
      "/dns4/testnet-03-bootnode-2.spacemesh.network/tcp/5000/p2p/12D3KooWQKosE9LZraMfFPg9QRYyKwxT4ipsar37oT6wRy8WqWos",
      "/dns4/testnet-03-bootnode-3.spacemesh.network/tcp/5000/p2p/12D3KooWKMQ5j15x2gzfXfX7uisss7uwkPnqJyoHcfyiYfHgSo3F",
      "/dns4/testnet-03-bootnode-4.spacemesh.network/tcp/5000/p2p/12D3KooWE1YEa3roqamhPt3CNiVRBzS7Lbv8HRbByE7fpSyLAZis",
      "/dns4/testnet-03-bootnode-5.spacemesh.network/tcp/5000/p2p/12D3KooWFCqyEner8hSnBmyQCkcxkuHjwY5BhHTaRYmGuNC1SQET",
      "/dns4/testnet-03-bootnode-6.spacemesh.network/tcp/5000/p2p/12D3KooWA96fvi2pQaQHpS2cpahDJCyQSsBW6A4KwHCPXsDVuiEJ",
      "/dns4/testnet-03-bootnode-7.spacemesh.network/tcp/5000/p2p/12D3KooWRvAVZrK3EURQBh1wdMPRDgjtowU84div3YxWYKuGDaFU",
      "/dns4/testnet-03-bootnode-8.spacemesh.network/tcp/5000/p2p/12D3KooWL3VGmZ4xgT1J5KnVJz7b6wxAUUFAVqNNRURKFfWNXLE4",
      "/dns4/testnet-03-bootnode-9.spacemesh.network/tcp/5000/p2p/12D3KooWCfadA8PUva7eRn1GzdLhnfELRLu81s1na6JbdYivwBgs"
    ]
  },
  "smeshing": {},
  "main": {
    "layer-duration": "300s",
    "layers-per-epoch": 864,
    "tick-size": 9266400,
    "block-gas-limit": 1000000,
    "poet-server": [
      "https://testnet-03-poet-0.spacemesh.network",
      "https://testnet-03-poet-1.spacemesh.network",
      "https://testnet-03-poet-2.spacemesh.network",
      "https://poet-10.spacemesh.network"
    ]
  },
  "genesis": {
    "genesis-time": "2023-04-11T18:00:00.498Z",
    "genesis-extra-data": "testnet-03"
  },
  "poet": {
    "phase-shift": "36h",
    "cycle-gap": "6h",
    "grace-period": "1m"
  },
  "post": {
      "post-labels-per-unit": 536870912,
      "post-max-numunits": 1000,
      "post-min-numunits": 4,
      "post-k1": 279,
      "post-k2": 300,
      "post-k3": 65,
      "post-k2pow-difficulty": 469112881707866048,
      "post-k3pow-difficulty": 29244622850649904
  },
   "hare": {
    "hare-wakeup-delta": "25s",
    "hare-round-duration": "25s",
    "hare-limit-iterations": 4,
    "hare-committee-size": 200
  },
  "tortoise": {
    "tortoise-zdist": 2,
    "tortoise-hdist": 40,
    "tortoise-window-size": 2000,
    "tortoise-delay-layers": 100
  },
  "beacon": {
    "beacon-grace-period-duration": "10m",
    "beacon-proposal-duration": "2m",
    "beacon-first-voting-round-duration": "30m",
    "beacon-rounds-number": 200,
    "beacon-voting-round-duration": "2m",
    "beacon-weak-coin-round-duration": "2m"
  }
}

```
1. Start node from a fresh state `./build/go-spacemesh --config config.json --data-folder data`
2. Wait a couple of minutes.
3. Use `ctrl+c` to stop the node, observe the panic. Bear in mind panics occur sometimes
 but not always.
[panic-log.txt](https://github.com/spacemeshos/go-spacemesh/files/11271617/panic-log.txt)

## Actual Behavior
The node panics

## Expected Behavior
The node should not panic

## Environment
Please complete the following information:
 - OS: Ubuntu 22.04.2 LTS
 - Node Version: 18a0601d77e5fab906034066980c44cd5a540598

**Comment by dshulyak** [comment]
Some component(s) holds onto connection handle for longer than 5s even after pool cancels it. If this is observed again, full traceback will be useful, as there should be a goroutine in it that does that
