### ISSUE TITLE
panic: failed to start smeshing: failed to prepare post initializer: fetch best provider: failed to fetch providers

### ISSUE THREAD

**Issue by bugxzhu** [spacemeshos/go-spacemesh#4708]
## Description

```
=/ip4/34.93.21.232/tcp/5000 sample_rate=100 connection_status="established" dir="outbound"	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "p2p"}
2023-07-15T03:15:48.612Z	ERROR	00000.defaultLogger	Fatal: goroutine panicked. Stacktrace: goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc00018d180?, {0x0?, 0xc0007b44a0?}}, {0x19d05fb, 0x1c}, {0xc0004f51d0, 0x1, 0x1})
	/src/log/zap.go:46 +0xd7
github.com/spacemeshos/go-spacemesh/log.Panic({0x19d05fb, 0x1c}, {0xc0004f51d0, 0x1, 0x1})
	/src/log/log.go:171 +0x50
github.com/spacemeshos/go-spacemesh/node.(*App).startServices(0xc0001ba160, {0x1d1e930?, 0xc000444940})
	/src/node/node.go:1008 +0x47d
github.com/spacemeshos/go-spacemesh/node.(*App).Start(0xc0001ba160, {0x1d1e930, 0xc000444940})
	/src/node/node.go:1380 +0x1665
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1({0x1d1e930, 0xc000444940})
	/src/node/node.go:163 +0x368
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1(0xc0007d0000?, {0x1842239?, 0xb?, 0xb?})
	/src/node/node.go:184 +0x387
github.com/spf13/cobra.(*Command).execute(0xc0007d0000, {0xc000040190, 0xb, 0xb})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007d0000)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/src/cmd/node/main.go:24 +0xbb

2023-07-15T03:15:48.612Z	PANIC	00000.defaultLogger	failed to start smeshing: failed to prepare post initializer: fetch best provider: failed to fetch providers
2023-07-15T03:15:48.612Z	INFO	56c0c.nipostValidator.worker-11	stopped post proof verifier worker	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "nipostValidator"}
2023-07-15T03:15:48.612Z	INFO	56c0c.nipostValidator.worker-3	stopped post proof verifier worker	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "nipostValidator"}
2023-07-15T03:15:48.612Z	INFO	56c0c.nipostValidator.worker-1	stopped post proof verifier worker	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "nipostValidator"}
2023-07-15T03:15:48.612Z	INFO	56c0c.nipostValidator.worker-13	stopped post proof verifier worker	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "nipostValidator"}
2023-07-15T03:15:48.612Z	INFO	56c0c.nipostValidator.worker-14	stopped post proof verifier worker	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "nipostValidator"}
2023-07-15T03:15:48.612Z	INFO	56c0c.nipostValidator.worker-10	stopped post proof verifier worker	{"node_id": "56c0cdc66c50d3033f7624791eb732e3642e9d0bddf7830a7cf4e126788af833", "module": "nipostValidator"}
panic: failed to start smeshing: failed to prepare post initializer: fetch best provider: failed to fetch providers

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000530340, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc0004f4fa8, 0x4, {0x19d05fb?, 0x0?}, {0xc0004f51d0?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:189
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc00018d180?, {0x0?, 0xc0007b44a0?}}, {0x19d05fb, 0x1c}, {0xc0004f51d0, 0x1, 0x1})
	/src/log/zap.go:47 +0x1fa
github.com/spacemeshos/go-spacemesh/log.Panic({0x19d05fb, 0x1c}, {0xc0004f51d0, 0x1, 0x1})
	/src/log/log.go:171 +0x50
github.com/spacemeshos/go-spacemesh/node.(*App).startServices(0xc0001ba160, {0x1d1e930?, 0xc000444940})
	/src/node/node.go:1008 +0x47d
github.com/spacemeshos/go-spacemesh/node.(*App).Start(0xc0001ba160, {0x1d1e930, 0xc000444940})
	/src/node/node.go:1380 +0x1665
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1.1({0x1d1e930, 0xc000444940})
	/src/node/node.go:163 +0x368
github.com/spacemeshos/go-spacemesh/node.GetCommand.func1(0xc0007d0000?, {0x1842239?, 0xb?, 0xb?})
	/src/node/node.go:184 +0x387
github.com/spf13/cobra.(*Command).execute(0xc0007d0000, {0xc000040190, 0xb, 0xb})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007d0000)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/src/cmd/node/main.go:24 +0xbb
```

## Steps to reproduce
go-spacemesh --listen /ip4/0.0.0.0/tcp/7513 --config /data/config.mainnet.json -d /data/smdata/ --smeshing-coinbase sm1qqqqqqxsh --smeshing-start --smeshing-opts-datadir /data/post_data

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

**Comment by poszu** [comment]
Hi @bugxzhu, thanks for reporting the issue. Could you please:
- add the following section to your JSON config file (/data/config.mainnet.json) at the main structure:
```json
  "logging": {
    "post": "debug"
  }
```

It should look like this:
```
{
  "smeshing": {
   ... fields
  },
   ... fields
  "logging": {
    "post": "debug",
    "nipostBuilder": "debug"
  }
}
```
- share your config (/data/config.mainnet.json)
- share the complete log (from the start of go-spacemesh)

**Comment by poszu** [comment]
Are you on Linux x86 and what GPU do you have?

**Comment by lrettig** [comment]
This happened to me today on Linux x86 with an Nvidia 2xxx GPU. It was working fine a few days ago, and worked again after a reboot. Most likely the OpenCL drivers were upgraded and the system needed a reboot.

The annoying thing is that this happens even if gpu-post init is already complete. Can we modify go-spacemesh so that it doesn't require access to the providers using OpenCL if init is already complete?
