### ISSUE TITLE
Node crashes with SIGSEGV when verifying initial proof

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/go-spacemesh#4798]
## Description
Recently `TestSpacemeshApp_NodeService` has become flacky on the `macos-latest` runner. It often crashes with the following stack trace:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x112900b24 pc=0x112900b24]

goroutine 869 [syscall]:
runtime.cgocall(0x101ae8be0, 0xc001bbd650)
	/Users/runner/hostedtoolcache/go/1.19.12/x64/src/runtime/cgocall.go:158 +0x6e fp=0xc001bbd5b8 sp=0xc001bbd580 pc=0x100008d4e
github.com/spacemeshos/post/internal/postrs._Cfunc_verify_proof(0x600000004e60, {0xd, {0xc0006c5b8c, 0x4, 0x4}, 0x0, {0xc000134600, 0x20, 0x20}}, 0xc000052540, ...)
	_cgo_gotypes.go:458 +0x98 fp=0xc001bbd650 sp=0xc001bbd5b8 pc=0x100b03178
github.com/spacemeshos/post/internal/postrs.(*Verifier).VerifyProof.func1(0xc001c5a3f0, {0xd, {0xc0006c5b8c, 0x4, 0x4}, 0x0, {0xc000134600, 0x20, 0x20}}, 0xc000052540, ...)
	/Users/runner/go/pkg/mod/github.com/spacemeshos/post@v0.8.11/internal/postrs/proof.go:243 +0x210 fp=0xc001bbd7d8 sp=0xc001bbd650 pc=0x100b08130
github.com/spacemeshos/post/internal/postrs.(*Verifier).VerifyProof(0x102109ab1?, 0xc000e44840, 0xc000efdb00, 0xc0003aff10, 0x1a, 0x4, 0x25, {0xff, 0xff, 0xff, ...}, ...)
	/Users/runner/go/pkg/mod/github.com/spacemeshos/post@v0.8.11/internal/postrs/proof.go:243 +0x985 fp=0xc001bbdae8 sp=0xc001bbd7d8 pc=0x100b07aa5
github.com/spacemeshos/post/verifying.(*ProofVerifier).Verify(0xc000214038, 0x100053053?, 0xc000efdb00, {0x2, 0x4, 0x20, 0x1a, 0x4, 0x25, {0xff, ...}}, ...)
	/Users/runner/go/pkg/mod/github.com/spacemeshos/post@v0.8.11/verifying/verifying.go:102 +0x3d1 fp=0xc001bbdc18 sp=0xc001bbdae8 pc=0x100b0ca31
github.com/spacemeshos/go-spacemesh/activation.(*postVerifier).Verify(0xc0007380c0, {0x1026b5828, 0xc00004e218}, 0x0?, 0xc000efdb00, {0xc000214230, 0x1, 0x1})
	/Users/runner/work/go-spacemesh/go-spacemesh/activation/post_verifier.go:44 +0x35c fp=0xc001bbddf0 sp=0xc001bbdc18 pc=0x10183c8fc
github.com/spacemeshos/go-spacemesh/activation.(*postVerifierWorker).start(0xc000730240, {0x1026b5828, 0xc00004e218})
	/Users/runner/work/go-spacemesh/go-spacemesh/activation/post_verifier.go:131 +0x166 fp=0xc001bbdee8 sp=0xc001bbddf0 pc=0x10183de66
github.com/spacemeshos/go-spacemesh/activation.(*OffloadingPostVerifier).Start.func1()
	/Users/runner/work/go-spacemesh/go-spacemesh/activation/post_verifier.go:85 +0x4d fp=0xc001bbdf38 sp=0xc001bbdee8 pc=0x10183d60d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x87 fp=0xc001bbdfe0 sp=0xc001bbdf38 pc=0x100a900a7
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.19.12/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc001bbdfe8 sp=0xc001bbdfe0 pc=0x100076b21
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x12f
```

see for instance https://github.com/spacemeshos/go-spacemesh/actions/runs/5808069235/job/15744121357

The problem seems to be in the `verify_proof` function exposed by `post-rs` and seems to be timing dependent. I was not able to reproduce this issue on my Mac M1 or an Intel Mac. It might only occur on slower machines with specific timings.

**Comment by fasmat** [comment]
cc @poszu

**Comment by fasmat** [comment]
This issue hasn't been observed in a while, closing.
