### ISSUE TITLE
v1.SmesherService.PostSetupStatus -- panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kevinelliott** [spacemeshos/go-spacemesh#4829]
## Description

There is a memory address/pointer deference error when requesting status of the smesher.

## Steps to reproduce

1. Start node
2. `grpcurl -plaintext -d '{"coinbase": {"address": "sm1qqqqqqxre24mtprsmuht8gfhu28z95hm22zvrdq34rmr8"},"opts": {"data_dir": "data","num_units": 6,"max_file_size": 2147483648,"provider_id": 0,"throttle": false}}' 127.0.0.1:19093 spacemesh.v1.SmesherService.PostSetupStatus` (note that I'm running services at 19092 and 19093, with a 1 prefixed, this is intentional)

## Actual Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100ec69b7]

goroutine 490 [running]:
github.com/spacemeshos/go-spacemesh/api/grpcserver.statusToPbStatus(...)
        /Users/kevin/Cloud/Dropbox/work/crypto/spacemesh/official/go-spacemesh/api/grpcserver/smesher_service.go:261
github.com/spacemeshos/go-spacemesh/api/grpcserver.SmesherService.PostSetupStatus({{0x101a75ed0, 0xc0003a6f18}, {0x101a69eb0, 0xc000162300}, {0x101a727c0, 0xc0003be8c0}, 0x3b9aca00, {{0x7ff7bfeff03b, 0xb}, 0x6, ...}}, ...)
        /Users/kevin/Cloud/Dropbox/work/crypto/spacemesh/official/go-spacemesh/api/grpcserver/smesher_service.go:180 +0x97
github.com/spacemeshos/api/release/go/spacemesh/v1._SmesherService_PostSetupStatus_Handler.func1({0x101a68cf8, 0xc001296750}, {0x1013d6d80?, 0xc0012964e0})
        /Users/kevin/go/pkg/mod/github.com/spacemeshos/api/release/go@v1.18.0/spacemesh/v1/smesher.pb.go:673 +0x78
github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1({0x101a68cf8, 0xc001296690}, {0x1013d6d80, 0xc0012964e0}, 0xc00128fd80, 0xc001234cf0)
        /Users/kevin/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/zap/server_interceptors.go:31 +0x115
google.golang.org/grpc.getChainUnaryHandler.func1({0x101a68cf8, 0xc001296690}, {0x1013d6d80, 0xc0012964e0})
        /Users/kevin/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1179 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1({0x101a68cf8?, 0xc0012964b0?}, {0x1013d6d80, 0xc0012964e0}, 0xc00128fd80, 0xc00129c0c0)
        /Users/kevin/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/tags/interceptors.go:23 +0xa6
google.golang.org/grpc.chainUnaryInterceptors.func1({0x101a68cf8, 0xc0012964b0}, {0x1013d6d80, 0xc0012964e0}, 0xc0006dea20?, 0x1013232e0?)
        /Users/kevin/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1170 +0x8f
github.com/spacemeshos/api/release/go/spacemesh/v1._SmesherService_PostSetupStatus_Handler({0x10151e340?, 0xc0004f8630}, {0x101a68cf8, 0xc0012964b0}, 0xc00016fea0, 0xc0007b0e20)
        /Users/kevin/go/pkg/mod/github.com/spacemeshos/api/release/go@v1.18.0/spacemesh/v1/smesher.pb.go:675 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027f0e0, {0x101a76760, 0xc000c24820}, 0xc0005ca900, 0xc000768cf0, 0x10260ef78, 0x0)
        /Users/kevin/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc00027f0e0, {0x101a76760, 0xc000c24820}, 0xc0005ca900, 0x0)
        /Users/kevin/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /Users/kevin/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/kevin/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x18c
ERROR:
  Code: Unavailable
  Message: error reading from server: EOF
Failed to dial target host "127.0.0.1:19093": dial tcp 127.0.0.1:19093: connect: connection refused
Failed to dial target host "127.0.0.1:19093": dial tcp 127.0.0.1:19093: connect: connection refused
```

It does not recover.

## Expected Behavior

As was previously working for weeks, I expected to receive a status response and no crash.

## Environment
Please complete the following information:
 - OS: MacOS
 - Node Version: v1.0.11-18-gfd9046c0+fd9046c042e77a8dff53e6e8fa067d86d2ad420f
 - Smapp version (if applicable): N/A

**Comment by pigmej** [comment]
That was fixed on the releases later on ;)
