### ISSUE TITLE
Segmentation fault in TestSpacemeshApp_NodeService

### ISSUE THREAD

**Issue by piersy** [spacemeshos/go-spacemesh#4910]
## Description
The test fails with a segmentation fault.

```
2023-08-25T08:24:40.4151030Z fatal error: unexpected signal during runtime execution
2023-08-25T08:24:40.4177990Z [signal SIGSEGV: segmentation violation code=0x2 addr=0x135edd74c pc=0x135edd74c]
2023-08-25T08:24:40.4178240Z 
2023-08-25T08:24:40.4178320Z runtime stack:
2023-08-25T08:24:40.4178530Z runtime.throw({0x10462f78a?, 0x1790c9890?})
2023-08-25T08:24:40.4179340Z 	/Users/aviv/actions-runner/_work/_tool/go/1.20.5/arm64/src/runtime/panic.go:1047 +0x40 fp=0x1790c97e0 sp=0x1790c97b0 pc=0x102d88060
2023-08-25T08:24:40.4183330Z runtime.sigpanic()
2023-08-25T08:24:40.4183800Z 	/Users/aviv/actions-runner/_work/_tool/go/1.20.5/arm64/src/runtime/signal_unix.go:825 +0x244 fp=0x1790c9820 sp=0x1790c97e0 pc=0x102da1324
2023-08-25T08:24:40.4184020Z 
2023-08-25T08:24:40.4184120Z goroutine 1732 [syscall]:
2023-08-25T08:24:40.4190400Z runtime.cgocall(0x1042fd5c4, 0xc00050b698)
2023-08-25T08:24:40.4190910Z 	/Users/aviv/actions-runner/_work/_tool/go/1.20.5/arm64/src/runtime/cgocall.go:157 +0x68 fp=0xc00050b660 sp=0xc00050b620 pc=0x102d52f58
2023-08-25T08:24:40.4191360Z github.com/spacemeshos/post/internal/postrs._Cfunc_verify_proof(0x13022da30, {0x2, {0xc00314c00c, 0x4, 0x4}, 0x0, {0xc000202120, 0x20, 0x20}}, 0xc00024a070, ...)
2023-08-25T08:24:40.4191750Z 	_cgo_gotypes.go:454 +0x4c fp=0xc00050b690 sp=0xc00050b660 pc=0x10364fe3c
2023-08-25T08:24:40.4192160Z github.com/spacemeshos/post/internal/postrs.(*Verifier).VerifyProof.func1(0xc000a58750, {0x2, {0xc00314c00c, 0x4, 0x4}, 0x0, {0xc000202120, 0x20, 0x20}}, 0x104c10f20?, ...)
2023-08-25T08:24:40.4192630Z 	/Users/aviv/go/pkg/mod/github.com/spacemeshos/post@v0.9.2/internal/postrs/proof.go:249 +0x150 fp=0xc00050b830 sp=0xc00050b690 pc=0x103653cc0
2023-08-25T08:24:40.4195930Z github.com/spacemeshos/post/internal/postrs.(*Verifier).VerifyProof(0x104c31d00?, 0xc001cca030, 0xc002aab260, 0xc0006aaee0, 0x1a, 0x4, 0x25, {0xff, 0xff, 0xff, ...}, ...)
2023-08-25T08:24:40.4196490Z 	/Users/aviv/go/pkg/mod/github.com/spacemeshos/post@v0.9.2/internal/postrs/proof.go:249 +0x878 fp=0xc00050baf0 sp=0xc00050b830 pc=0x1036539e8
2023-08-25T08:24:40.4196930Z github.com/spacemeshos/post/verifying.(*ProofVerifier).Verify(0xc000011328, 0x102d9d4e8?, 0xc002aab260, {0x2, 0x4, 0x20, 0x1a, 0x4, 0x25, {0xff, ...}}, ...)
2023-08-25T08:24:40.4197380Z 	/Users/aviv/go/pkg/mod/github.com/spacemeshos/post@v0.9.2/verifying/verifying.go:104 +0x288 fp=0xc00050bc10 sp=0xc00050baf0 pc=0x103658298
2023-08-25T08:24:40.4197910Z github.com/spacemeshos/go-spacemesh/activation.(*postVerifier).Verify(0xc0006da540, {0x104ed68e8, 0xc0001b6018}, 0x0?, 0xc002aab260, {0xc0006fe008, 0x1, 0x1})
2023-08-25T08:24:40.4198460Z 	/Users/aviv/actions-runner/_work/go-spacemesh/go-spacemesh/activation/post_verifier.go:44 +0x214 fp=0xc00050bdd0 sp=0xc00050bc10 pc=0x1040d7374
2023-08-25T08:24:40.4198940Z github.com/spacemeshos/go-spacemesh/activation.(*postVerifierWorker).start(0xc0011fee10, {0x104ed68e8, 0xc0001b6018})
2023-08-25T08:24:40.4199480Z 	/Users/aviv/actions-runner/_work/go-spacemesh/go-spacemesh/activation/post_verifier.go:131 +0x114 fp=0xc00050bed0 sp=0xc00050bdd0 pc=0x1040d83e4
2023-08-25T08:24:40.4199930Z github.com/spacemeshos/go-spacemesh/activation.(*OffloadingPostVerifier).Start.func1()
2023-08-25T08:24:40.4200490Z 	/Users/aviv/actions-runner/_work/go-spacemesh/go-spacemesh/activation/post_verifier.go:85 +0x48 fp=0xc00050bf20 sp=0xc00050bed0 pc=0x1040d7d98
2023-08-25T08:24:40.4200830Z golang.org/x/sync/errgroup.(*Group).Go.func1()
2023-08-25T08:24:40.4201180Z 	/Users/aviv/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x70 fp=0xc00050bfd0 sp=0xc00050bf20 pc=0x1035eebd0
2023-08-25T08:24:40.4201450Z runtime.goexit()
2023-08-25T08:24:40.4201860Z 	/Users/aviv/actions-runner/_work/_tool/go/1.20.5/arm64/src/runtime/asm_arm64.s:1172 +0x4 fp=0xc00050bfd0 sp=0xc00050bfd0 pc=0x102dc1344
2023-08-25T08:24:40.4202190Z created by golang.org/x/sync/errgroup.(*Group).Go
2023-08-25T08:24:40.4202500Z 	/Users/aviv/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x110
```
Full logs can be found here: https://github.com/spacemeshos/go-spacemesh/actions/runs/5973555476/job/16206053208?pr=4897

From what I can see it looks like there is a problem calling close on OffloadingPostVerifier while its workers are in the process of verifying a proof.

## Steps to reproduce
1. Checkout #4867 
2. Run `TestSpacemeshApp_NodeService` several times
3. Notice the occasional segmentation fault.

## Expected Behavior
No segmentation faults

## Environment
It's happening on my local machine running Ubuntu 22.04.2 LTS, but I can also see it happening on CI on our self hosted mac runner (see link above)

## Additional Resources
This is also happening on #4869

**Comment by fasmat** [comment]
As a temporary workaround in https://github.com/spacemeshos/go-spacemesh/pull/4869 smeshing has been disabled for tests in `node_test.go` (see https://github.com/spacemeshos/go-spacemesh/pull/4869/commits/fe3d0f00b1cc7b02bca0875902784ad8b1b877f5).

We should consider enabling it again after fixing the root cause, just to have a chance of detecting similar issues in the future.

**Comment by piersy** [comment]
Hey @fasmat & @poszu, although this has been fixed as part of #4869 in this commit 788e2a7f3465cbab383adf8920aea7418bd28cf7, note this is a fix (the disable smeshing workaround was reverted), it only ensures that `node.App` only calls `postVerifier.Close` after `postVerifier.Start` has returned. However incorrect use of `postVerifier` can still result in a segfault and that should probably be fixed before considering this ticket complete.

**Comment by poszu** [comment]
>However incorrect use of postVerifier can still result in a segfault and that should probably be fixed before considering this ticket complete.

The segfault was caused by calling `postVerifier.Close()` while it was still running. To make the API bullet-proof we could inline `Close()` into the `Start()` at the end of it and document that it cannot be reused after `Start()` returns.

**Comment by fasmat** [comment]
The current solution feels hacky to me:

```go
	app.eg.Go(func() error {
		app.postVerifier.Start(ctx)
		return app.postVerifier.Close()
	})

	app.postVerifier.Verify(...)
```

The problem here is that the call to `postVerifier.Verify` might happen before `Start` has finished initializing the `postVerifier`. Additionally the shutdown is a 3 step process of canceling the context, waiting for `Start` to return and then calling `Close`.

I would like to instead suggest to `KISS` and update the API to be used like this:

```go
app.postVerifier.Start() // no context and returns when postVerifier is ready to use
app.postVerifier.Verify(ctx, ...) // context cancels this one verify call (to abort early when shutting down, or for other reasons
app.postVerifier.Close() // blocks calls to `Verify`, waits for all current calls to `Verify` to return then closes the verifier
```

This way the API is simple and intuitive to use. No Waitgroups to manage the verifier are needed, there are no races between `Start`, `Verify` and `Close`.

This could be further simplified by inlining `postVerifier.Start` into `NewOffloadingPostVerifier`:

```go
app.postVerifier = activation.NewOffloadingPostVerifier
app.postVerifier.Verify(ctx, ...)
app.postVerifier.Close()
```
