### ISSUE TITLE
initializing scrypter: no provider specified

### ISSUE THREAD

**Issue by ChanQ0en** [spacemeshos/go-spacemesh#4920]
The binary command I run looks like this:
./go-spacemesh --listen /ip4/0.0.0.0/tcp/7513 --config ./tn1.json -d ./sm_data --smeshing-coinbase wallet-address --smeshing-start --smeshing-opts-datadir ./post_data --smeshing-opts-numunits=4

The error log is as follows:
```
2023-08-29T07:42:48.054Z	WARN	27225.sync	malicious identity does not exist	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "sync", "sessionId": "44eb8ba3-012b-44ad-b270-0a11c97f0400", "identity": "fdfe4f67ca586516614b5b5f3b779789a9d57cb5eced687f78d834a57bd56c95", "name": "sync"}
2023-08-29T07:42:48.054Z	WARN	27225.sync	malicious identity does not exist	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "sync", "sessionId": "44eb8ba3-012b-44ad-b270-0a11c97f0400", "identity": "fe136fc08459920f8cb3cb2fa287fc59fdcd6cd77b374300ab01da4616da53f9", "name": "sync"}
2023-08-29T07:42:49.421Z	INFO	27225.sync	malicious IDs synced	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "sync", "sessionId": "44eb8ba3-012b-44ad-b270-0a11c97f0400", "name": "sync"}
2023-08-29T07:42:49.421Z	INFO	27225.post	post setup session starting	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "post", "node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "commitment_atx": "9eebff023a", "data_dir": "./post_data", "num_units": "4", "labels_per_unit": "32768", "provider": "{0}", "name": "post"}
2023-08-29T07:42:49.427Z	INFO	27225.post	initialization started	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "post", "datadir": "./post_data", "numUnits": 4, "maxFileSize": 4294967296, "labelsPerUnit": 32768}
2023-08-29T07:42:49.427Z	INFO	27225.post	initialization file layout	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "post", "labelsPerFile": 268435456, "labelsLastFile": 131072, "firstFileIndex": 0, "lastFileIndex": 0}
2023-08-29T07:42:49.427Z	INFO	27225.post	initialization: starting to write file	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "post", "fileIndex": 0, "currentNumLabels": 0, "targetNumLabels": 131072, "startPosition": 0}
2023-08-29T07:42:49.427Z	ERROR	27225.post	post setup session failed	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "post", "errmsg": "failed to compute labels: initializing scrypter: no provider specified", "name": "post"}
2023-08-29T07:42:49.427Z	ERROR	27225.atxBuilder	Fatal: goroutine panicked. Stacktrace: goroutine 1811 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0008b1500?, {0x1a2a99a?, 0x0?}}, {0x1b86ee3, 0x19}, {0xc00487c620, 0x1, 0x1})
	/opt/project/go-spacemesh/log/zap.go:46 +0xb7
github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1()
	/opt/project/go-spacemesh/activation/activation.go:222 +0x1e3
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/root/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/root/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "atxBuilder"}
2023-08-29T07:42:49.427Z	PANIC	27225.atxBuilder	initialization failed: failed to compute labels: initializing scrypter: no provider specified	{"node_id": "27225e32a205fcb374463ec201c562f13c1a621619cc19178d3de39ab8028627", "module": "atxBuilder"}
panic: initialization failed: failed to compute labels: initializing scrypter: no provider specified

goroutine 1811 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000606820, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc001babd40, 0x4, {0x1b86ee3?, 0x0?}, {0xc00487c620?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/sugar.go:316 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.25.0/sugar.go:202
github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0008b1500?, {0x1a2a99a?, 0x0?}}, {0x1b86ee3, 0x19}, {0xc00487c620, 0x1, 0x1})
	/opt/project/go-spacemesh/log/zap.go:47 +0x1bb
github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1()
	/opt/project/go-spacemesh/activation/activation.go:222 +0x1e3
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/root/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/root/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```
The go-spacemesh binary program ran for a while, and then panicked by itself. After reading the logs, I found that this is the problem. Is it caused by the failure to synchronize successfully? what do i need to do

The hardware configuration of my machine:
cpu: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz * 2
memory: ddr4 32g * 8
disk: 480G SSD
graphics card: Nvidia RTX 3060

my binary version is v1.1.1+4441f5235007c944b369b12bd22c098106d1ad0a

my OS is Ubuntu 22.04 LTS

my OS kernel is 5.15.0-79-generic

nvidia-smi
```
Tue Aug 29 18:56:40 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        Off | 00000000:03:00.0 Off |                  N/A |
| 30%   44C    P0              34W / 170W |      1MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by poszu** [comment]
@ChanQ0en It works as intended. In order to start smashing, you need to specify a POST init provider to initialize the data with. You can do it either via `--smeshing-opts-provider` or in the config JSON file under the `smeshing-opts`.
